-- WARNING: This schema is for context only and is not meant to be run.
-- Table order and constraints may not be valid for execution.

CREATE TABLE public.erp_audit_logs (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  table_name text NOT NULL,
  record_id uuid NOT NULL,
  action text NOT NULL,
  old_data jsonb,
  new_data jsonb,
  changed_by uuid,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT erp_audit_logs_pkey PRIMARY KEY (id),
  CONSTRAINT erp_audit_logs_changed_by_fkey FOREIGN KEY (changed_by) REFERENCES public.erp_staff(id)
);
CREATE TABLE public.erp_blacklist (
  phone text NOT NULL,
  full_name text,
  reason text,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT erp_blacklist_pkey PRIMARY KEY (phone)
);
CREATE TABLE public.erp_deliveries (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  order_id text NOT NULL,
  rider_id uuid NOT NULL,
  status text DEFAULT 'ASSIGNED'::text,
  rider_earnings numeric DEFAULT 0.00,
  fuel_compensation numeric DEFAULT 0.00,
  surcharges numeric DEFAULT 0.00,
  cash_collected numeric DEFAULT 0.00,
  cleared_with_admin boolean DEFAULT false,
  completed_at timestamp with time zone,
  created_at timestamp with time zone DEFAULT now(),
  schedule_id uuid,
  menu_item_id uuid,
  member_id uuid,
  delivery_address text,
  delivery_lat numeric,
  delivery_lng numeric,
  distance_km numeric,
  pickup_at timestamp with time zone,
  delivered_at timestamp with time zone,
  failed_at timestamp with time zone,
  fail_reason text,
  proof_url text,
  rider_notes text,
  cancelled_at timestamp with time zone,
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT erp_deliveries_pkey PRIMARY KEY (id),
  CONSTRAINT erp_deliveries_rider_id_fkey FOREIGN KEY (rider_id) REFERENCES public.erp_staff(id),
  CONSTRAINT fk_deliveries_member FOREIGN KEY (member_id) REFERENCES public.members(id),
  CONSTRAINT fk_deliveries_schedule FOREIGN KEY (schedule_id) REFERENCES public.erp_delivery_schedules(id),
  CONSTRAINT fk_deliveries_menu_item FOREIGN KEY (menu_item_id) REFERENCES public.menu_items(id),
  CONSTRAINT erp_deliveries_order_id_fkey FOREIGN KEY (order_id) REFERENCES public.orders(order_id)
);
CREATE TABLE public.erp_delivery_schedules (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  member_id uuid NOT NULL,
  scheduled_date date NOT NULL,
  menu_name text NOT NULL,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT erp_delivery_schedules_pkey PRIMARY KEY (id),
  CONSTRAINT fk_schedule_member FOREIGN KEY (member_id) REFERENCES public.members(id)
);
CREATE TABLE public.erp_expense_categories (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  name text NOT NULL,
  pool_type text NOT NULL,
  icon text DEFAULT '📦'::text,
  color text DEFAULT '#64748b'::text,
  visibility text DEFAULT 'ALL'::text,
  is_personal boolean DEFAULT false,
  sort_order integer DEFAULT 0,
  is_active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT erp_expense_categories_pkey PRIMARY KEY (id)
);
CREATE TABLE public.erp_financial_transactions (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  type text NOT NULL,
  petty_cash_status text DEFAULT 'NONE'::erp_petty_cash_status,
  category text NOT NULL,
  amount numeric NOT NULL,
  vat_amount numeric DEFAULT 0.00,
  tax_invoice_no text,
  reference_id text,
  notes text,
  is_reconciled boolean DEFAULT false,
  reconciled_at timestamp with time zone,
  created_by uuid,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  deleted_at timestamp with time zone,
  payment_id uuid,
  order_id text,
  supplier_id uuid,
  payment_method text,
  receipt_url text,
  approved_by uuid,
  approved_at timestamp with time zone,
  CONSTRAINT erp_financial_transactions_pkey PRIMARY KEY (id),
  CONSTRAINT erp_financial_transactions_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.erp_staff(id),
  CONSTRAINT fk_financial_payment FOREIGN KEY (payment_id) REFERENCES public.payments(id),
  CONSTRAINT fk_financial_supplier FOREIGN KEY (supplier_id) REFERENCES public.erp_suppliers(id),
  CONSTRAINT fk_financial_approved_by FOREIGN KEY (approved_by) REFERENCES public.erp_staff(id),
  CONSTRAINT fk_financial_order FOREIGN KEY (order_id) REFERENCES public.orders(order_id)
);
CREATE TABLE public.erp_fund_pools (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  pool_type text NOT NULL UNIQUE,
  display_name text NOT NULL,
  display_name_public text NOT NULL,
  current_balance numeric DEFAULT 0,
  total_in numeric DEFAULT 0,
  total_out numeric DEFAULT 0,
  target_amount numeric DEFAULT 0,
  color_code text DEFAULT '#10b981'::text,
  icon text DEFAULT '💰'::text,
  visibility text DEFAULT 'ALL'::text,
  sort_order integer DEFAULT 0,
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT erp_fund_pools_pkey PRIMARY KEY (id)
);
CREATE TABLE public.erp_fund_transactions (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  pool_type text NOT NULL,
  direction text NOT NULL,
  amount numeric NOT NULL,
  category text,
  description text,
  private_note text,
  source_type text DEFAULT 'MANUAL'::text,
  source_id text,
  receipt_url text,
  is_personal boolean DEFAULT false,
  created_by uuid,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT erp_fund_transactions_pkey PRIMARY KEY (id),
  CONSTRAINT erp_fund_transactions_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.erp_staff(id)
);
CREATE TABLE public.erp_inventory_adjustments (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  inventory_item_id uuid NOT NULL,
  location_id uuid,
  expected_qty numeric NOT NULL,
  actual_qty numeric NOT NULL,
  discrepancy numeric DEFAULT (actual_qty - expected_qty),
  reason text,
  adjusted_by uuid,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT erp_inventory_adjustments_pkey PRIMARY KEY (id),
  CONSTRAINT fk_adj_item FOREIGN KEY (inventory_item_id) REFERENCES public.erp_inventory_items(id),
  CONSTRAINT fk_adj_location FOREIGN KEY (location_id) REFERENCES public.erp_inventory_locations(id),
  CONSTRAINT fk_adj_staff FOREIGN KEY (adjusted_by) REFERENCES public.erp_staff(id)
);
CREATE TABLE public.erp_inventory_batches (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  inventory_item_id uuid,
  location_id uuid,
  qty numeric NOT NULL,
  unit_cost numeric NOT NULL,
  purchase_unit text,
  purchase_qty numeric,
  receipt_no text,
  supplier_id uuid,
  received_at timestamp with time zone DEFAULT now(),
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT erp_inventory_batches_pkey PRIMARY KEY (id),
  CONSTRAINT erp_inventory_batches_inventory_item_id_fkey FOREIGN KEY (inventory_item_id) REFERENCES public.erp_inventory_items(id),
  CONSTRAINT erp_inventory_batches_location_id_fkey FOREIGN KEY (location_id) REFERENCES public.erp_inventory_locations(id),
  CONSTRAINT erp_inventory_batches_supplier_id_fkey FOREIGN KEY (supplier_id) REFERENCES public.erp_suppliers(id)
);
CREATE TABLE public.erp_inventory_items (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  name text NOT NULL UNIQUE,
  storage_unit text NOT NULL,
  current_stock numeric DEFAULT 0,
  last_counted_at timestamp with time zone,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  min_stock_level numeric DEFAULT 0,
  reorder_quantity numeric DEFAULT 0,
  category text DEFAULT 'ingredient'::text,
  avg_unit_cost numeric DEFAULT 0.00,
  default_supplier_id uuid,
  barcode text,
  shelf_location text,
  expiry_alert_days integer DEFAULT 3,
  notes text,
  deleted_at timestamp with time zone,
  is_test boolean DEFAULT false,
  CONSTRAINT erp_inventory_items_pkey PRIMARY KEY (id),
  CONSTRAINT erp_inv_items_default_supplier_fkey FOREIGN KEY (default_supplier_id) REFERENCES public.erp_suppliers(id)
);
CREATE TABLE public.erp_inventory_locations (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  name text NOT NULL,
  description text,
  is_active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT erp_inventory_locations_pkey PRIMARY KEY (id)
);
CREATE TABLE public.erp_inventory_transactions (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  inventory_item_id uuid NOT NULL,
  type text NOT NULL,
  qty_changed numeric NOT NULL,
  reason text,
  created_by uuid,
  created_at timestamp with time zone DEFAULT now(),
  location_id uuid,
  CONSTRAINT erp_inventory_transactions_pkey PRIMARY KEY (id),
  CONSTRAINT fk_inventory_tx_item FOREIGN KEY (inventory_item_id) REFERENCES public.erp_inventory_items(id),
  CONSTRAINT fk_inventory_tx_staff FOREIGN KEY (created_by) REFERENCES public.erp_staff(id),
  CONSTRAINT fk_inventory_tx_location FOREIGN KEY (location_id) REFERENCES public.erp_inventory_locations(id)
);
CREATE TABLE public.erp_kds_tasks (
  order_id text NOT NULL,
  target_time_minutes integer NOT NULL DEFAULT 15,
  prep_started_at timestamp with time zone,
  prep_finished_at timestamp with time zone,
  is_late boolean DEFAULT false,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT erp_kds_tasks_pkey PRIMARY KEY (order_id),
  CONSTRAINT fk_kds_order FOREIGN KEY (order_id) REFERENCES public.orders(order_id)
);
CREATE TABLE public.erp_kitchen_checklist (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  category text NOT NULL,
  item_name text NOT NULL,
  is_checked boolean DEFAULT false,
  updated_at timestamp with time zone DEFAULT timezone('utc'::text, now()),
  target_date date DEFAULT CURRENT_DATE,
  target_time text,
  location text,
  vendor text,
  notes text,
  CONSTRAINT erp_kitchen_checklist_pkey PRIMARY KEY (id)
);
CREATE TABLE public.erp_kitchen_checklist_master (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  category text NOT NULL,
  item_name text NOT NULL,
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()),
  vendor text,
  target_time text,
  CONSTRAINT erp_kitchen_checklist_master_pkey PRIMARY KEY (id)
);
CREATE TABLE public.erp_kitchen_sessions (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  session_date date NOT NULL,
  menu_item_id uuid,
  planned_qty integer NOT NULL DEFAULT 0,
  actual_qty integer DEFAULT 0,
  waste_qty integer DEFAULT 0,
  notes text,
  opened_at timestamp with time zone,
  closed_at timestamp with time zone,
  opened_by uuid,
  closed_by uuid,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT erp_kitchen_sessions_pkey PRIMARY KEY (id),
  CONSTRAINT erp_kitchen_sessions_menu_item_id_fkey FOREIGN KEY (menu_item_id) REFERENCES public.menu_items(id),
  CONSTRAINT erp_kitchen_sessions_opened_by_fkey FOREIGN KEY (opened_by) REFERENCES public.erp_staff(id),
  CONSTRAINT erp_kitchen_sessions_closed_by_fkey FOREIGN KEY (closed_by) REFERENCES public.erp_staff(id),
  CONSTRAINT fk_kitchen_menu FOREIGN KEY (menu_item_id) REFERENCES public.menu_items(id),
  CONSTRAINT fk_kitchen_opened_by FOREIGN KEY (opened_by) REFERENCES public.erp_staff(id),
  CONSTRAINT fk_kitchen_closed_by FOREIGN KEY (closed_by) REFERENCES public.erp_staff(id)
);
CREATE TABLE public.erp_member_ban_logs (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  member_id uuid,
  action text NOT NULL,
  reason text,
  created_by uuid,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT erp_member_ban_logs_pkey PRIMARY KEY (id),
  CONSTRAINT erp_member_ban_logs_member_id_fkey FOREIGN KEY (member_id) REFERENCES public.members(id)
);
CREATE TABLE public.erp_member_meal_schedules (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  package_id uuid NOT NULL,
  member_id uuid NOT NULL,
  delivery_date date NOT NULL,
  meal_type text NOT NULL,
  menu_item_id uuid,
  quantity integer DEFAULT 1,
  box_size text DEFAULT 'regular'::text,
  kitchen_status text DEFAULT 'pending'::text,
  notes text,
  created_at timestamp with time zone DEFAULT now(),
  delivery_time text,
  is_extra_order boolean DEFAULT false,
  meal_order_type text DEFAULT 'subscription'::text,
  is_compensatory boolean DEFAULT false,
  CONSTRAINT erp_member_meal_schedules_pkey PRIMARY KEY (id),
  CONSTRAINT erp_member_meal_schedules_package_id_fkey FOREIGN KEY (package_id) REFERENCES public.pinto_packages(id),
  CONSTRAINT erp_member_meal_schedules_member_id_fkey FOREIGN KEY (member_id) REFERENCES public.members(id),
  CONSTRAINT erp_member_meal_schedules_menu_item_id_fkey FOREIGN KEY (menu_item_id) REFERENCES public.menu_items(id)
);
CREATE TABLE public.erp_member_streaks (
  member_id uuid NOT NULL,
  current_streak_days integer DEFAULT 0,
  longest_streak_days integer DEFAULT 0,
  last_delivered_date date,
  updated_at timestamp with time zone DEFAULT now(),
  total_delivered integer DEFAULT 0,
  reward_claimed boolean DEFAULT false,
  next_reward_at_days integer DEFAULT 7,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT erp_member_streaks_pkey PRIMARY KEY (member_id),
  CONSTRAINT fk_member_streaks_member FOREIGN KEY (member_id) REFERENCES public.members(id)
);
CREATE TABLE public.erp_order_feedback (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  order_id text NOT NULL,
  kitchen_staff_id uuid,
  rider_id uuid,
  rating integer CHECK (rating >= 1 AND rating <= 5),
  comment text,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT erp_order_feedback_pkey PRIMARY KEY (id),
  CONSTRAINT erp_order_feedback_kitchen_staff_id_fkey FOREIGN KEY (kitchen_staff_id) REFERENCES public.erp_staff(id),
  CONSTRAINT erp_order_feedback_rider_id_fkey FOREIGN KEY (rider_id) REFERENCES public.erp_staff(id),
  CONSTRAINT fk_feedback_kitchen FOREIGN KEY (kitchen_staff_id) REFERENCES public.erp_staff(id),
  CONSTRAINT fk_feedback_rider FOREIGN KEY (rider_id) REFERENCES public.erp_staff(id),
  CONSTRAINT fk_feedback_order FOREIGN KEY (order_id) REFERENCES public.orders(order_id)
);
CREATE TABLE public.erp_recipes (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  menu_name text NOT NULL,
  item_id uuid NOT NULL,
  quantity_required numeric NOT NULL,
  yield_percentage numeric DEFAULT 100.00,
  labor_cost numeric DEFAULT 0.00,
  utility_cost numeric DEFAULT 0.00,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  deleted_at timestamp with time zone,
  menu_item_id uuid,
  serving_size integer DEFAULT 1,
  version integer DEFAULT 1,
  notes text,
  CONSTRAINT erp_recipes_pkey PRIMARY KEY (id),
  CONSTRAINT fk_recipes_item FOREIGN KEY (item_id) REFERENCES public.erp_inventory_items(id),
  CONSTRAINT fk_recipes_menu_item FOREIGN KEY (menu_item_id) REFERENCES public.menu_items(id)
);
CREATE TABLE public.erp_revenue_buckets (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  source_type text NOT NULL,
  source_id text,
  member_id uuid,
  payment_id uuid,
  gross_amount numeric NOT NULL,
  delivery_fee numeric DEFAULT 0,
  net_amount numeric NOT NULL,
  split_config_id uuid,
  material_pct numeric DEFAULT 35,
  labor_pct numeric DEFAULT 15,
  ops_pct numeric DEFAULT 20,
  profit_pct numeric DEFAULT 30,
  material_amount numeric NOT NULL,
  labor_amount numeric NOT NULL,
  ops_amount numeric NOT NULL,
  profit_amount numeric NOT NULL,
  description text,
  status text DEFAULT 'active'::text,
  period_start date,
  period_end date,
  notes text,
  private_note text,
  created_by uuid,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT erp_revenue_buckets_pkey PRIMARY KEY (id),
  CONSTRAINT erp_revenue_buckets_member_id_fkey FOREIGN KEY (member_id) REFERENCES public.members(id),
  CONSTRAINT erp_revenue_buckets_payment_id_fkey FOREIGN KEY (payment_id) REFERENCES public.payments(id),
  CONSTRAINT erp_revenue_buckets_split_config_id_fkey FOREIGN KEY (split_config_id) REFERENCES public.erp_split_configs(id),
  CONSTRAINT erp_revenue_buckets_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.erp_staff(id)
);
CREATE TABLE public.erp_settings (
  key text NOT NULL,
  value jsonb NOT NULL,
  description text,
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT erp_settings_pkey PRIMARY KEY (key)
);
CREATE TABLE public.erp_shipping_discounts (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  min_order numeric NOT NULL,
  discount_amount numeric NOT NULL,
  label text,
  is_active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT erp_shipping_discounts_pkey PRIMARY KEY (id)
);
CREATE TABLE public.erp_split_configs (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  config_name text NOT NULL,
  promotion_type text NOT NULL DEFAULT 'PINTO'::text,
  material_pct numeric NOT NULL DEFAULT 35,
  labor_pct numeric NOT NULL DEFAULT 15,
  ops_pct numeric NOT NULL DEFAULT 20,
  profit_pct numeric NOT NULL DEFAULT 30,
  is_default boolean DEFAULT false,
  is_active boolean DEFAULT true,
  notes text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT erp_split_configs_pkey PRIMARY KEY (id)
);
CREATE TABLE public.erp_staff (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  full_name text NOT NULL,
  phone text,
  is_active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  email text UNIQUE,
  pin_code text DEFAULT '1234'::text,
  nickname text,
  national_id text,
  bank_account text,
  bank_name text,
  emergency_contact text,
  start_date date,
  end_date date,
  daily_rate numeric DEFAULT 0.00,
  notes text,
  deleted_at timestamp with time zone,
  role text CHECK (role = ANY (ARRAY['ADMIN'::text, 'RIDER'::text, 'KITCHEN'::text, 'MANAGER'::text])),
  CONSTRAINT erp_staff_pkey PRIMARY KEY (id)
);
CREATE TABLE public.erp_suppliers (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  name text NOT NULL,
  tax_id text,
  is_active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  contact_name text,
  phone text,
  email text,
  address text,
  payment_terms text DEFAULT 'COD'::text,
  credit_days integer DEFAULT 0,
  notes text,
  deleted_at timestamp with time zone,
  CONSTRAINT erp_suppliers_pkey PRIMARY KEY (id)
);
CREATE TABLE public.erp_system_configs (
  key text NOT NULL,
  value jsonb NOT NULL,
  updated_by uuid,
  updated_at timestamp with time zone DEFAULT now(),
  description text,
  is_public boolean DEFAULT false,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT erp_system_configs_pkey PRIMARY KEY (key),
  CONSTRAINT erp_system_configs_updated_by_fkey FOREIGN KEY (updated_by) REFERENCES public.erp_staff(id)
);
CREATE TABLE public.erp_unit_conversions (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  item_id uuid NOT NULL,
  from_unit text NOT NULL,
  to_unit text NOT NULL,
  conversion_factor numeric NOT NULL,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT erp_unit_conversions_pkey PRIMARY KEY (id),
  CONSTRAINT fk_conversion_item FOREIGN KEY (item_id) REFERENCES public.erp_inventory_items(id)
);
CREATE TABLE public.erp_vehicle_logs (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  rider_id uuid NOT NULL,
  maintenance_type text NOT NULL,
  cost numeric NOT NULL,
  mileage integer,
  created_at timestamp with time zone DEFAULT now(),
  deleted_at timestamp with time zone,
  CONSTRAINT erp_vehicle_logs_pkey PRIMARY KEY (id),
  CONSTRAINT erp_vehicle_logs_rider_id_fkey FOREIGN KEY (rider_id) REFERENCES public.erp_staff(id),
  CONSTRAINT fk_vehicle_rider FOREIGN KEY (rider_id) REFERENCES public.erp_staff(id)
);
CREATE TABLE public.meal_deduction_logs (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  package_id uuid NOT NULL,
  order_id text NOT NULL,
  member_id uuid NOT NULL,
  meals_deducted integer NOT NULL DEFAULT 1,
  meals_before integer NOT NULL,
  meals_after integer NOT NULL,
  deducted_by uuid,
  deduction_source text DEFAULT 'system'::text,
  notes text,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT meal_deduction_logs_pkey PRIMARY KEY (id),
  CONSTRAINT fk_meal_package FOREIGN KEY (package_id) REFERENCES public.pinto_packages(id),
  CONSTRAINT fk_meal_member FOREIGN KEY (member_id) REFERENCES public.members(id),
  CONSTRAINT fk_meal_order FOREIGN KEY (order_id) REFERENCES public.orders(order_id)
);
CREATE TABLE public.member_addresses (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  member_id uuid NOT NULL,
  label text NOT NULL DEFAULT 'บ้าน'::text,
  address_line text NOT NULL,
  district text,
  subdistrict text,
  province text DEFAULT 'เชียงราย'::text,
  postal_code text DEFAULT '57000'::text,
  lat numeric,
  lng numeric,
  delivery_notes text,
  is_default boolean DEFAULT false,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  deleted_at timestamp with time zone,
  CONSTRAINT member_addresses_pkey PRIMARY KEY (id),
  CONSTRAINT member_addresses_member_id_fkey FOREIGN KEY (member_id) REFERENCES public.members(id),
  CONSTRAINT fk_address_member FOREIGN KEY (member_id) REFERENCES public.members(id)
);
CREATE TABLE public.members (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  created_at timestamp with time zone DEFAULT now(),
  full_name text NOT NULL,
  phone text NOT NULL UNIQUE,
  line_id text,
  avatar_url text,
  member_status text DEFAULT 'active'::text,
  line_display_name text,
  line_picture_url text,
  email text,
  date_of_birth date,
  gender text,
  health_goal text,
  allergy_notes text,
  default_address_id uuid,
  source text DEFAULT 'organic'::text,
  referral_member_id uuid,
  total_orders integer DEFAULT 0,
  lifetime_value numeric DEFAULT 0.00,
  last_order_at timestamp with time zone,
  is_blocked boolean DEFAULT false,
  blocked_reason text,
  internal_notes text,
  tags ARRAY DEFAULT '{}'::text[],
  line_user_id text UNIQUE,
  updated_at timestamp with time zone DEFAULT now(),
  deleted_at timestamp with time zone,
  address text,
  sub_district text,
  district text,
  province text,
  postal_code text,
  delivery_time text,
  age_range text,
  occupation text,
  food_preferences jsonb DEFAULT '[]'::jsonb,
  member_type text DEFAULT 'retail'::text,
  is_banned boolean DEFAULT false,
  ban_reason text,
  banned_at timestamp with time zone,
  CONSTRAINT members_pkey PRIMARY KEY (id)
);
CREATE TABLE public.menu_cycle_templates (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  week_number integer NOT NULL,
  day_of_week integer NOT NULL,
  meal_slot integer NOT NULL,
  category text,
  protein text,
  menu_name text NOT NULL,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT menu_cycle_templates_pkey PRIMARY KEY (id)
);
CREATE TABLE public.menu_items (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  name text NOT NULL,
  category text NOT NULL DEFAULT 'main'::text,
  description text,
  image_url text,
  image_thumbnail_url text,
  calories integer DEFAULT 0,
  protein integer DEFAULT 0,
  carbs integer DEFAULT 0,
  fat integer DEFAULT 0,
  fiber integer DEFAULT 0,
  sodium integer DEFAULT 0,
  allergens ARRAY DEFAULT '{}'::text[],
  base_price numeric NOT NULL DEFAULT 0.00,
  prep_time_minutes integer DEFAULT 15,
  is_available boolean DEFAULT true,
  is_subscription_only boolean DEFAULT false,
  sort_order integer DEFAULT 0,
  tags ARRAY DEFAULT '{}'::text[],
  notes text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  deleted_at timestamp with time zone,
  target_cost numeric DEFAULT 0.00,
  cost_percentage numeric DEFAULT 
CASE
    WHEN (base_price > (0)::numeric) THEN round(((target_cost / base_price) * (100)::numeric), 1)
    ELSE (0)::numeric
END,
  menu_group text DEFAULT 'standard'::text,
  CONSTRAINT menu_items_pkey PRIMARY KEY (id)
);
CREATE TABLE public.notifications_log (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  member_id uuid,
  channel text NOT NULL DEFAULT 'LINE'::notification_channel_type,
  type text NOT NULL,
  reference_id text,
  template_key text,
  message_preview text,
  status text NOT NULL DEFAULT 'SENT'::text,
  error_message text,
  sent_at timestamp with time zone DEFAULT now(),
  delivered_at timestamp with time zone,
  CONSTRAINT notifications_log_pkey PRIMARY KEY (id),
  CONSTRAINT notifications_log_member_id_fkey FOREIGN KEY (member_id) REFERENCES public.members(id),
  CONSTRAINT fk_notifications_member FOREIGN KEY (member_id) REFERENCES public.members(id)
);
CREATE TABLE public.order_items (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  order_id text NOT NULL,
  menu_item_id uuid,
  qty integer NOT NULL DEFAULT 1,
  unit_price numeric NOT NULL DEFAULT 0.00,
  item_type text,
  CONSTRAINT order_items_pkey PRIMARY KEY (id),
  CONSTRAINT fk_order_items_menu FOREIGN KEY (menu_item_id) REFERENCES public.menu_items(id),
  CONSTRAINT fk_order_items_order FOREIGN KEY (order_id) REFERENCES public.orders(order_id)
);
CREATE TABLE public.orders (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  member_id uuid,
  menu_name text NOT NULL,
  status text DEFAULT 'success'::text,
  delivery_date timestamp with time zone DEFAULT now(),
  created_at timestamp with time zone DEFAULT now(),
  phone text,
  order_id text NOT NULL DEFAULT gen_random_uuid() UNIQUE,
  total_amount numeric DEFAULT 0,
  payment_status text DEFAULT 'รอตรวจสลิป'::text,
  kitchen_status text DEFAULT 'รอยืนยัน'::text,
  delivery_status text DEFAULT 'รอส่ง'::text,
  calories integer,
  protein integer,
  carbs integer,
  fat integer,
  meals_deducted integer DEFAULT 0,
  menu_item_id uuid,
  promotion_id uuid,
  address_id uuid,
  delivery_address text,
  delivery_lat numeric,
  delivery_lng numeric,
  delivery_slot text,
  estimated_delivery_at timestamp with time zone,
  actual_delivery_at timestamp with time zone,
  packaging_fee numeric DEFAULT 0.00,
  discount_amount numeric DEFAULT 0.00,
  subtotal numeric DEFAULT 0.00,
  customer_notes text,
  internal_notes text,
  rating integer CHECK (rating >= 1 AND rating <= 5),
  rating_comment text,
  rated_at timestamp with time zone,
  cancelled_at timestamp with time zone,
  cancelled_by uuid,
  cancelled_reason text,
  fiber integer DEFAULT 0,
  sodium integer DEFAULT 0,
  updated_at timestamp with time zone DEFAULT now(),
  order_details text,
  items_total numeric DEFAULT 0,
  delivery_fee numeric DEFAULT 0,
  bundle_discount numeric DEFAULT 0,
  display_order_id character varying,
  customer_id uuid,
  notes text,
  CONSTRAINT orders_pkey PRIMARY KEY (order_id),
  CONSTRAINT orders_member_id_fkey FOREIGN KEY (member_id) REFERENCES public.members(id),
  CONSTRAINT orders_menu_item_id_fkey FOREIGN KEY (menu_item_id) REFERENCES public.menu_items(id),
  CONSTRAINT orders_promotion_id_fkey FOREIGN KEY (promotion_id) REFERENCES public.promotions(id),
  CONSTRAINT fk_orders_member FOREIGN KEY (member_id) REFERENCES public.members(id),
  CONSTRAINT fk_orders_menu_item FOREIGN KEY (menu_item_id) REFERENCES public.menu_items(id),
  CONSTRAINT fk_orders_promotion FOREIGN KEY (promotion_id) REFERENCES public.promotions(id)
);
CREATE TABLE public.orders_web (
  order_id text NOT NULL,
  phone text,
  member_id uuid,
  menu_name text,
  order_details text,
  items_total numeric DEFAULT 0,
  delivery_fee numeric DEFAULT 0,
  bundle_discount numeric DEFAULT 0,
  total_amount numeric DEFAULT 0,
  delivery_slot text,
  delivery_date timestamp with time zone,
  delivery_address text,
  delivery_lat numeric,
  delivery_lng numeric,
  customer_notes text,
  payment_status text DEFAULT 'รอตรวจสลิป'::text,
  kitchen_status text DEFAULT 'รอยืนยัน'::text,
  delivery_status text DEFAULT 'รอส่ง'::text,
  created_at timestamp with time zone DEFAULT now(),
  promotion_id uuid,
  menu_item_id uuid,
  discount_amount numeric DEFAULT 0.00,
  packaging_fee numeric DEFAULT 0.00,
  CONSTRAINT orders_web_pkey PRIMARY KEY (order_id),
  CONSTRAINT orders_web_promotion_id_fkey FOREIGN KEY (promotion_id) REFERENCES public.promotions(id),
  CONSTRAINT orders_web_menu_item_id_fkey FOREIGN KEY (menu_item_id) REFERENCES public.menu_items(id),
  CONSTRAINT fk_orders_web_member FOREIGN KEY (member_id) REFERENCES public.members(id)
);
CREATE TABLE public.payments (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  order_id text,
  package_id uuid,
  member_id uuid,
  amount numeric NOT NULL DEFAULT 0.00,
  method text NOT NULL DEFAULT 'TRANSFER'::payment_method_type,
  status text NOT NULL DEFAULT 'PENDING'::payment_status_type,
  slip_url text,
  slip_uploaded_at timestamp with time zone,
  verified_at timestamp with time zone,
  verified_by uuid,
  rejected_at timestamp with time zone,
  rejected_reason text,
  bank_ref text,
  bank_name text,
  refunded_at timestamp with time zone,
  refund_amount numeric DEFAULT 0.00,
  notes text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT payments_pkey PRIMARY KEY (id),
  CONSTRAINT payments_order_id_fkey FOREIGN KEY (order_id) REFERENCES public.orders(order_id),
  CONSTRAINT payments_package_id_fkey FOREIGN KEY (package_id) REFERENCES public.pinto_packages(id),
  CONSTRAINT payments_member_id_fkey FOREIGN KEY (member_id) REFERENCES public.members(id),
  CONSTRAINT payments_verified_by_fkey FOREIGN KEY (verified_by) REFERENCES public.erp_staff(id),
  CONSTRAINT fk_payments_package FOREIGN KEY (package_id) REFERENCES public.pinto_packages(id),
  CONSTRAINT fk_payments_member FOREIGN KEY (member_id) REFERENCES public.members(id),
  CONSTRAINT fk_payments_verified_by FOREIGN KEY (verified_by) REFERENCES public.erp_staff(id),
  CONSTRAINT fk_payments_order FOREIGN KEY (order_id) REFERENCES public.orders(order_id)
);
CREATE TABLE public.pinto_meal_plan (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  delivery_date date NOT NULL,
  menu_name text NOT NULL,
  image_url text,
  calories integer DEFAULT 0,
  protein integer DEFAULT 0,
  carbs integer DEFAULT 0,
  fat integer DEFAULT 0,
  created_at timestamp with time zone DEFAULT now(),
  menu_item_id uuid,
  description text,
  allergen_notes text,
  fiber integer DEFAULT 0,
  sodium integer DEFAULT 0,
  price numeric DEFAULT 0.00,
  max_orders integer,
  current_orders integer DEFAULT 0,
  is_published boolean DEFAULT false,
  prep_notes text,
  updated_at timestamp with time zone DEFAULT now(),
  meal_type text DEFAULT 'meal_1'::text,
  week_plan_id uuid,
  CONSTRAINT pinto_meal_plan_pkey PRIMARY KEY (id),
  CONSTRAINT pinto_meal_plan_menu_item_id_fkey FOREIGN KEY (menu_item_id) REFERENCES public.menu_items(id),
  CONSTRAINT pinto_meal_plan_week_plan_id_fkey FOREIGN KEY (week_plan_id) REFERENCES public.weekly_plans(id)
);
CREATE TABLE public.pinto_packages (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  member_id uuid NOT NULL,
  package_name text NOT NULL DEFAULT 'เซ็ตสุขภาพ 30 วัน'::text,
  days_total integer NOT NULL DEFAULT 30,
  days_remaining integer NOT NULL DEFAULT 0,
  status text NOT NULL DEFAULT 'active'::text CHECK (status = ANY (ARRAY['active'::text, 'paused'::text, 'cancelled'::text, 'completed'::text])),
  last_deducted timestamp with time zone,
  updated_at timestamp with time zone DEFAULT now(),
  phone text,
  start_date date,
  delivery_slot text,
  package_code text UNIQUE,
  meals_total integer DEFAULT 0,
  meals_remaining integer DEFAULT 0,
  price_paid numeric DEFAULT 0.00,
  promotion_id uuid,
  payment_id uuid,
  assigned_rider_id uuid,
  default_address_id uuid,
  auto_renew boolean DEFAULT false,
  renewed_from_id uuid,
  end_date date,
  paused_at timestamp with time zone,
  paused_reason text,
  cancelled_at timestamp with time zone,
  cancelled_reason text,
  source text DEFAULT 'organic'::text,
  internal_notes text,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT pinto_packages_pkey PRIMARY KEY (id),
  CONSTRAINT pinto_packages_member_id_fkey FOREIGN KEY (member_id) REFERENCES public.members(id),
  CONSTRAINT pinto_packages_rider_id_fkey FOREIGN KEY (assigned_rider_id) REFERENCES public.erp_staff(id),
  CONSTRAINT pinto_packages_payment_id_fkey FOREIGN KEY (payment_id) REFERENCES public.payments(id),
  CONSTRAINT pinto_packages_promotion_id_fkey FOREIGN KEY (promotion_id) REFERENCES public.promotions(id),
  CONSTRAINT fk_packages_member FOREIGN KEY (member_id) REFERENCES public.members(id),
  CONSTRAINT fk_packages_rider FOREIGN KEY (assigned_rider_id) REFERENCES public.erp_staff(id),
  CONSTRAINT fk_packages_payment FOREIGN KEY (payment_id) REFERENCES public.payments(id),
  CONSTRAINT fk_packages_promotion FOREIGN KEY (promotion_id) REFERENCES public.promotions(id)
);
CREATE TABLE public.promotions (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  code text NOT NULL UNIQUE,
  name text NOT NULL,
  description text,
  discount_type text NOT NULL DEFAULT 'FIXED'::discount_type,
  discount_value numeric NOT NULL DEFAULT 0.00,
  min_order_amount numeric DEFAULT 0.00,
  max_discount_amount numeric,
  max_uses integer,
  used_count integer NOT NULL DEFAULT 0,
  max_uses_per_member integer DEFAULT 1,
  valid_from date,
  valid_until date,
  applicable_to text DEFAULT 'all'::text,
  is_active boolean DEFAULT true,
  created_by uuid,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  deleted_at timestamp with time zone,
  price numeric DEFAULT 0,
  meals_count integer DEFAULT 0,
  days_count integer DEFAULT 0,
  sales_script text,
  promotion_type text DEFAULT 'PINTO'::text,
  conditions text,
  split_config_id uuid,
  CONSTRAINT promotions_pkey PRIMARY KEY (id),
  CONSTRAINT promotions_split_config_id_fkey FOREIGN KEY (split_config_id) REFERENCES public.erp_split_configs(id)
);
CREATE TABLE public.shop_holidays (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  holiday_date date NOT NULL UNIQUE,
  name text NOT NULL,
  type text DEFAULT 'holiday'::text,
  is_active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT shop_holidays_pkey PRIMARY KEY (id)
);
CREATE TABLE public.weekly_plans (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  week_start date NOT NULL UNIQUE,
  notes text,
  status text DEFAULT 'draft'::text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT weekly_plans_pkey PRIMARY KEY (id)
);