-- WARNING: This schema is for context only and is not meant to be run.
-- Table order and constraints may not be valid for execution.

CREATE TABLE public.members (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  created_at timestamp with time zone DEFAULT now(),
  full_name text,
  phone text UNIQUE,
  line_id text,
  avatar_url text,
  member_status text DEFAULT 'active'::text,
  line_display_name text,
  line_picture_url text,
  email text,
  date_of_birth date,
  gender text,
  health_goal text,
  allergy_notes text,
  default_address_id uuid,
  source text DEFAULT 'organic'::text,
  referral_member_id uuid,
  total_orders integer DEFAULT 0,
  lifetime_value numeric DEFAULT 0.00,
  last_order_at timestamp with time zone,
  is_blocked boolean DEFAULT false,
  blocked_reason text,
  internal_notes text,
  tags ARRAY DEFAULT '{}'::text[],
  line_user_id text UNIQUE,
  updated_at timestamp with time zone DEFAULT now(),
  deleted_at timestamp with time zone,
  address text,
  sub_district text,
  district text,
  province text,
  postal_code text,
  delivery_time text,
  age_range text,
  occupation text,
  food_preferences jsonb DEFAULT '[]'::jsonb,
  member_type text DEFAULT 'retail'::text,
  is_banned boolean DEFAULT false,
  ban_reason text,
  banned_at timestamp with time zone,
  role text DEFAULT 'user'::text,
  CONSTRAINT members_pkey PRIMARY KEY (id)
);
CREATE TABLE public.pinto_packages (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  member_id uuid NOT NULL,
  package_name text NOT NULL DEFAULT 'เซ็ตสุขภาพ 30 วัน'::text,
  days_total integer NOT NULL DEFAULT 30,
  days_remaining integer NOT NULL DEFAULT 0,
  status text NOT NULL DEFAULT 'active'::text CHECK (status = ANY (ARRAY['active'::text, 'paused'::text, 'cancelled'::text, 'completed'::text])),
  last_deducted timestamp with time zone,
  updated_at timestamp with time zone DEFAULT now(),
  phone text,
  start_date date,
  delivery_slot text,
  package_code text UNIQUE,
  meals_total integer DEFAULT 0,
  meals_remaining integer DEFAULT 0,
  price_paid numeric DEFAULT 0.00,
  promotion_id uuid,
  payment_id uuid,
  assigned_rider_id uuid,
  default_address_id uuid,
  auto_renew boolean DEFAULT false,
  renewed_from_id uuid,
  end_date date,
  paused_at timestamp with time zone,
  paused_reason text,
  cancelled_at timestamp with time zone,
  cancelled_reason text,
  source text DEFAULT 'organic'::text,
  internal_notes text,
  created_at timestamp with time zone DEFAULT now(),
  buddy_group_id uuid,
  bonus_meals integer DEFAULT 0,
  drop_point_id uuid,
  CONSTRAINT pinto_packages_pkey PRIMARY KEY (id),
  CONSTRAINT pinto_packages_member_id_fkey FOREIGN KEY (member_id) REFERENCES public.members(id),
  CONSTRAINT pinto_packages_rider_id_fkey FOREIGN KEY (assigned_rider_id) REFERENCES public.erp_staff(id),
  CONSTRAINT pinto_packages_payment_id_fkey FOREIGN KEY (payment_id) REFERENCES public.payments(id),
  CONSTRAINT pinto_packages_promotion_id_fkey FOREIGN KEY (promotion_id) REFERENCES public.promotions(id),
  CONSTRAINT fk_packages_member FOREIGN KEY (member_id) REFERENCES public.members(id),
  CONSTRAINT fk_packages_rider FOREIGN KEY (assigned_rider_id) REFERENCES public.erp_staff(id),
  CONSTRAINT fk_packages_payment FOREIGN KEY (payment_id) REFERENCES public.payments(id),
  CONSTRAINT fk_packages_promotion FOREIGN KEY (promotion_id) REFERENCES public.promotions(id),
  CONSTRAINT fk_packages_buddy_group FOREIGN KEY (buddy_group_id) REFERENCES public.erp_buddy_groups(id),
  CONSTRAINT fk_packages_drop_point FOREIGN KEY (drop_point_id) REFERENCES public.erp_drop_points(id)
);
CREATE TABLE public.orders (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  member_id uuid,
  menu_name text NOT NULL,
  status text DEFAULT 'success'::text,
  delivery_date timestamp with time zone DEFAULT now(),
  created_at timestamp with time zone DEFAULT now(),
  phone text,
  order_id text NOT NULL DEFAULT gen_random_uuid() UNIQUE,
  total_amount numeric DEFAULT 0,
  payment_status text DEFAULT 'รอตรวจสลิป'::text,
  kitchen_status text DEFAULT 'รอยืนยัน'::text,
  delivery_status text DEFAULT 'รอส่ง'::text,
  calories integer,
  protein integer,
  carbs integer,
  fat integer,
  meals_deducted integer DEFAULT 0,
  menu_item_id uuid,
  promotion_id uuid,
  address_id uuid,
  delivery_address text,
  delivery_lat numeric,
  delivery_lng numeric,
  delivery_slot text,
  estimated_delivery_at timestamp with time zone,
  actual_delivery_at timestamp with time zone,
  packaging_fee numeric DEFAULT 0.00,
  discount_amount numeric DEFAULT 0.00,
  subtotal numeric DEFAULT 0.00,
  customer_notes text,
  internal_notes text,
  rating integer CHECK (rating >= 1 AND rating <= 5),
  rating_comment text,
  rated_at timestamp with time zone,
  cancelled_at timestamp with time zone,
  cancelled_by uuid,
  cancelled_reason text,
  fiber integer DEFAULT 0,
  sodium integer DEFAULT 0,
  updated_at timestamp with time zone DEFAULT now(),
  order_details text,
  items_total numeric DEFAULT 0,
  delivery_fee numeric DEFAULT 0,
  bundle_discount numeric DEFAULT 0,
  display_order_id character varying,
  customer_id uuid,
  notes text,
  drop_point_id uuid,
  group_order_id uuid,
  delivery_method text DEFAULT 'self_delivery'::text,
  CONSTRAINT orders_pkey PRIMARY KEY (order_id),
  CONSTRAINT orders_member_id_fkey FOREIGN KEY (member_id) REFERENCES public.members(id),
  CONSTRAINT orders_menu_item_id_fkey FOREIGN KEY (menu_item_id) REFERENCES public.menu_items(id),
  CONSTRAINT orders_promotion_id_fkey FOREIGN KEY (promotion_id) REFERENCES public.promotions(id),
  CONSTRAINT fk_orders_member FOREIGN KEY (member_id) REFERENCES public.members(id),
  CONSTRAINT fk_orders_menu_item FOREIGN KEY (menu_item_id) REFERENCES public.menu_items(id),
  CONSTRAINT fk_orders_promotion FOREIGN KEY (promotion_id) REFERENCES public.promotions(id),
  CONSTRAINT fk_orders_drop_point FOREIGN KEY (drop_point_id) REFERENCES public.erp_drop_points(id),
  CONSTRAINT fk_orders_group_order FOREIGN KEY (group_order_id) REFERENCES public.erp_group_orders(id)
);
CREATE TABLE public.pinto_meal_plan (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  delivery_date date NOT NULL,
  menu_name text NOT NULL,
  image_url text,
  calories integer DEFAULT 0,
  protein integer DEFAULT 0,
  carbs integer DEFAULT 0,
  fat integer DEFAULT 0,
  created_at timestamp with time zone DEFAULT now(),
  menu_item_id uuid,
  description text,
  allergen_notes text,
  fiber integer DEFAULT 0,
  sodium integer DEFAULT 0,
  price numeric DEFAULT 0.00,
  max_orders integer,
  current_orders integer DEFAULT 0,
  is_published boolean DEFAULT false,
  prep_notes text,
  updated_at timestamp with time zone DEFAULT now(),
  meal_type text DEFAULT 'meal_1'::text,
  week_plan_id uuid,
  CONSTRAINT pinto_meal_plan_pkey PRIMARY KEY (id),
  CONSTRAINT pinto_meal_plan_menu_item_id_fkey FOREIGN KEY (menu_item_id) REFERENCES public.menu_items(id),
  CONSTRAINT pinto_meal_plan_week_plan_id_fkey FOREIGN KEY (week_plan_id) REFERENCES public.weekly_plans(id)
);
CREATE TABLE public.erp_staff (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  full_name text NOT NULL,
  phone text,
  is_active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  email text UNIQUE,
  pin_code text DEFAULT '1234'::text,
  nickname text,
  national_id text,
  bank_account text,
  bank_name text,
  emergency_contact text,
  start_date date,
  end_date date,
  daily_rate numeric DEFAULT 0.00,
  notes text,
  deleted_at timestamp with time zone,
  role text CHECK (role = ANY (ARRAY['ADMIN'::text, 'RIDER'::text, 'KITCHEN'::text, 'MANAGER'::text])),
  CONSTRAINT erp_staff_pkey PRIMARY KEY (id)
);
CREATE TABLE public.erp_member_streaks (
  member_id uuid NOT NULL,
  current_streak_days integer DEFAULT 0,
  longest_streak_days integer DEFAULT 0,
  last_delivered_date date,
  updated_at timestamp with time zone DEFAULT now(),
  total_delivered integer DEFAULT 0,
  reward_claimed boolean DEFAULT false,
  next_reward_at_days integer DEFAULT 7,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT erp_member_streaks_pkey PRIMARY KEY (member_id),
  CONSTRAINT fk_member_streaks_member FOREIGN KEY (member_id) REFERENCES public.members(id)
);
CREATE TABLE public.erp_order_feedback (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  order_id text NOT NULL,
  kitchen_staff_id uuid,
  rider_id uuid,
  rating integer CHECK (rating >= 1 AND rating <= 5),
  comment text,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT erp_order_feedback_pkey PRIMARY KEY (id),
  CONSTRAINT erp_order_feedback_kitchen_staff_id_fkey FOREIGN KEY (kitchen_staff_id) REFERENCES public.erp_staff(id),
  CONSTRAINT erp_order_feedback_rider_id_fkey FOREIGN KEY (rider_id) REFERENCES public.erp_staff(id),
  CONSTRAINT fk_feedback_kitchen FOREIGN KEY (kitchen_staff_id) REFERENCES public.erp_staff(id),
  CONSTRAINT fk_feedback_rider FOREIGN KEY (rider_id) REFERENCES public.erp_staff(id),
  CONSTRAINT fk_feedback_order FOREIGN KEY (order_id) REFERENCES public.orders(order_id)
);
CREATE TABLE public.erp_suppliers (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  name text NOT NULL,
  tax_id text,
  is_active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  contact_name text,
  phone text,
  email text,
  address text,
  payment_terms text DEFAULT 'COD'::text,
  credit_days integer DEFAULT 0,
  notes text,
  deleted_at timestamp with time zone,
  CONSTRAINT erp_suppliers_pkey PRIMARY KEY (id)
);
CREATE TABLE public.erp_inventory_items (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  name text NOT NULL UNIQUE,
  storage_unit text NOT NULL,
  current_stock numeric DEFAULT 0,
  last_counted_at timestamp with time zone,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  min_stock_level numeric DEFAULT 0,
  reorder_quantity numeric DEFAULT 0,
  category text DEFAULT 'ingredient'::text,
  avg_unit_cost numeric DEFAULT 0.00,
  default_supplier_id uuid,
  barcode text,
  shelf_location text,
  expiry_alert_days integer DEFAULT 3,
  notes text,
  deleted_at timestamp with time zone,
  is_test boolean DEFAULT false,
  CONSTRAINT erp_inventory_items_pkey PRIMARY KEY (id),
  CONSTRAINT erp_inv_items_default_supplier_fkey FOREIGN KEY (default_supplier_id) REFERENCES public.erp_suppliers(id)
);
CREATE TABLE public.erp_inventory_transactions (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  inventory_item_id uuid NOT NULL,
  type text NOT NULL,
  qty_changed numeric NOT NULL,
  reason text,
  created_by uuid,
  created_at timestamp with time zone DEFAULT now(),
  location_id uuid,
  CONSTRAINT erp_inventory_transactions_pkey PRIMARY KEY (id),
  CONSTRAINT fk_inventory_tx_item FOREIGN KEY (inventory_item_id) REFERENCES public.erp_inventory_items(id),
  CONSTRAINT fk_inventory_tx_staff FOREIGN KEY (created_by) REFERENCES public.erp_staff(id),
  CONSTRAINT fk_inventory_tx_location FOREIGN KEY (location_id) REFERENCES public.erp_inventory_locations(id)
);
CREATE TABLE public.erp_recipes (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  menu_name text NOT NULL,
  item_id uuid NOT NULL,
  quantity_required numeric NOT NULL,
  yield_percentage numeric DEFAULT 100.00,
  labor_cost numeric DEFAULT 0.00,
  utility_cost numeric DEFAULT 0.00,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  deleted_at timestamp with time zone,
  menu_item_id uuid,
  serving_size integer DEFAULT 1,
  version integer DEFAULT 1,
  notes text,
  CONSTRAINT erp_recipes_pkey PRIMARY KEY (id),
  CONSTRAINT fk_recipes_item FOREIGN KEY (item_id) REFERENCES public.erp_inventory_items(id),
  CONSTRAINT fk_recipes_menu_item FOREIGN KEY (menu_item_id) REFERENCES public.menu_items(id)
);
CREATE TABLE public.erp_delivery_schedules (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  member_id uuid NOT NULL,
  scheduled_date date NOT NULL,
  menu_name text NOT NULL,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT erp_delivery_schedules_pkey PRIMARY KEY (id),
  CONSTRAINT fk_schedule_member FOREIGN KEY (member_id) REFERENCES public.members(id)
);
CREATE TABLE public.erp_deliveries (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  order_id text NOT NULL,
  rider_id uuid NOT NULL,
  status text DEFAULT 'ASSIGNED'::text,
  rider_earnings numeric DEFAULT 0.00,
  fuel_compensation numeric DEFAULT 0.00,
  surcharges numeric DEFAULT 0.00,
  cash_collected numeric DEFAULT 0.00,
  cleared_with_admin boolean DEFAULT false,
  completed_at timestamp with time zone,
  created_at timestamp with time zone DEFAULT now(),
  schedule_id uuid,
  menu_item_id uuid,
  member_id uuid,
  delivery_address text,
  delivery_lat numeric,
  delivery_lng numeric,
  distance_km numeric,
  pickup_at timestamp with time zone,
  delivered_at timestamp with time zone,
  failed_at timestamp with time zone,
  fail_reason text,
  proof_url text,
  rider_notes text,
  cancelled_at timestamp with time zone,
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT erp_deliveries_pkey PRIMARY KEY (id),
  CONSTRAINT erp_deliveries_rider_id_fkey FOREIGN KEY (rider_id) REFERENCES public.erp_staff(id),
  CONSTRAINT fk_deliveries_member FOREIGN KEY (member_id) REFERENCES public.members(id),
  CONSTRAINT fk_deliveries_schedule FOREIGN KEY (schedule_id) REFERENCES public.erp_delivery_schedules(id),
  CONSTRAINT fk_deliveries_menu_item FOREIGN KEY (menu_item_id) REFERENCES public.menu_items(id),
  CONSTRAINT erp_deliveries_order_id_fkey FOREIGN KEY (order_id) REFERENCES public.orders(order_id)
);
CREATE TABLE public.erp_kds_tasks (
  order_id text NOT NULL,
  target_time_minutes integer NOT NULL DEFAULT 15,
  prep_started_at timestamp with time zone,
  prep_finished_at timestamp with time zone,
  is_late boolean DEFAULT false,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT erp_kds_tasks_pkey PRIMARY KEY (order_id),
  CONSTRAINT fk_kds_order FOREIGN KEY (order_id) REFERENCES public.orders(order_id)
);
CREATE TABLE public.erp_vehicle_logs (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  rider_id uuid NOT NULL,
  maintenance_type text NOT NULL,
  cost numeric NOT NULL,
  mileage integer,
  created_at timestamp with time zone DEFAULT now(),
  deleted_at timestamp with time zone,
  CONSTRAINT erp_vehicle_logs_pkey PRIMARY KEY (id),
  CONSTRAINT erp_vehicle_logs_rider_id_fkey FOREIGN KEY (rider_id) REFERENCES public.erp_staff(id),
  CONSTRAINT fk_vehicle_rider FOREIGN KEY (rider_id) REFERENCES public.erp_staff(id)
);
CREATE TABLE public.erp_system_configs (
  key text NOT NULL,
  value jsonb NOT NULL,
  updated_by uuid,
  updated_at timestamp with time zone DEFAULT now(),
  description text,
  is_public boolean DEFAULT false,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT erp_system_configs_pkey PRIMARY KEY (key),
  CONSTRAINT erp_system_configs_updated_by_fkey FOREIGN KEY (updated_by) REFERENCES public.erp_staff(id)
);
CREATE TABLE public.erp_financial_transactions (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  type text NOT NULL,
  petty_cash_status text DEFAULT 'NONE'::erp_petty_cash_status,
  category text NOT NULL,
  amount numeric NOT NULL,
  vat_amount numeric DEFAULT 0.00,
  tax_invoice_no text,
  reference_id text,
  notes text,
  is_reconciled boolean DEFAULT false,
  reconciled_at timestamp with time zone,
  created_by uuid,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  deleted_at timestamp with time zone,
  payment_id uuid,
  order_id text,
  supplier_id uuid,
  payment_method text,
  receipt_url text,
  approved_by uuid,
  approved_at timestamp with time zone,
  CONSTRAINT erp_financial_transactions_pkey PRIMARY KEY (id),
  CONSTRAINT erp_financial_transactions_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.erp_staff(id),
  CONSTRAINT fk_financial_payment FOREIGN KEY (payment_id) REFERENCES public.payments(id),
  CONSTRAINT fk_financial_supplier FOREIGN KEY (supplier_id) REFERENCES public.erp_suppliers(id),
  CONSTRAINT fk_financial_approved_by FOREIGN KEY (approved_by) REFERENCES public.erp_staff(id),
  CONSTRAINT fk_financial_order FOREIGN KEY (order_id) REFERENCES public.orders(order_id)
);
CREATE TABLE public.erp_audit_logs (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  table_name text NOT NULL,
  record_id uuid NOT NULL,
  action text NOT NULL,
  old_data jsonb,
  new_data jsonb,
  changed_by uuid,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT erp_audit_logs_pkey PRIMARY KEY (id),
  CONSTRAINT erp_audit_logs_changed_by_fkey FOREIGN KEY (changed_by) REFERENCES public.erp_staff(id)
);
CREATE TABLE public.menu_items (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  name text NOT NULL,
  category text NOT NULL DEFAULT 'main'::text,
  description text,
  image_url text,
  image_thumbnail_url text,
  calories integer DEFAULT 0,
  protein integer DEFAULT 0,
  carbs integer DEFAULT 0,
  fat integer DEFAULT 0,
  fiber integer DEFAULT 0,
  sodium integer DEFAULT 0,
  allergens ARRAY DEFAULT '{}'::text[],
  base_price numeric NOT NULL DEFAULT 0.00,
  prep_time_minutes integer DEFAULT 15,
  is_available boolean DEFAULT true,
  is_out_of_stock boolean DEFAULT false,
  is_subscription_only boolean DEFAULT false,
  sort_order integer DEFAULT 0,
  tags ARRAY DEFAULT '{}'::text[],
  notes text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  deleted_at timestamp with time zone,
  target_cost numeric DEFAULT 0.00,
  cost_percentage numeric DEFAULT 
CASE
    WHEN (base_price > (0)::numeric) THEN round(((target_cost / base_price) * (100)::numeric), 1)
    ELSE (0)::numeric
END,
  menu_group text DEFAULT 'standard'::text,
  packaging_cost numeric DEFAULT 0,
  labor_cost numeric DEFAULT 0,
  transport_cost numeric DEFAULT 0,
  overhead_cost numeric DEFAULT 0,
  recipe_instructions jsonb DEFAULT '[]'::jsonb,
  CONSTRAINT menu_items_pkey PRIMARY KEY (id)
);
CREATE TABLE public.promotions (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  code text NOT NULL UNIQUE,
  name text NOT NULL,
  description text,
  discount_type text NOT NULL DEFAULT 'FIXED'::discount_type,
  discount_value numeric NOT NULL DEFAULT 0.00,
  min_order_amount numeric DEFAULT 0.00,
  max_discount_amount numeric,
  max_uses integer,
  used_count integer NOT NULL DEFAULT 0,
  max_uses_per_member integer DEFAULT 1,
  valid_from date,
  valid_until date,
  applicable_to text DEFAULT 'all'::text,
  is_active boolean DEFAULT true,
  created_by uuid,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  deleted_at timestamp with time zone,
  price numeric DEFAULT 0,
  meals_count integer DEFAULT 0,
  days_count integer DEFAULT 0,
  sales_script text,
  promotion_type text DEFAULT 'PINTO'::text,
  conditions jsonb,
  split_config_id uuid,
  reward_type text DEFAULT 'DISCOUNT'::text,
  reward_config jsonb DEFAULT '{}'::jsonb,
  CONSTRAINT promotions_pkey PRIMARY KEY (id),
  CONSTRAINT promotions_split_config_id_fkey FOREIGN KEY (split_config_id) REFERENCES public.erp_split_configs(id)
);
CREATE TABLE public.payments (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  order_id text,
  package_id uuid,
  member_id uuid,
  amount numeric NOT NULL DEFAULT 0.00,
  method text NOT NULL DEFAULT 'TRANSFER'::payment_method_type,
  status text NOT NULL DEFAULT 'PENDING'::payment_status_type,
  slip_url text,
  slip_uploaded_at timestamp with time zone,
  verified_at timestamp with time zone,
  verified_by uuid,
  rejected_at timestamp with time zone,
  rejected_reason text,
  bank_ref text,
  bank_name text,
  refunded_at timestamp with time zone,
  refund_amount numeric DEFAULT 0.00,
  notes text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT payments_pkey PRIMARY KEY (id),
  CONSTRAINT payments_order_id_fkey FOREIGN KEY (order_id) REFERENCES public.orders(order_id),
  CONSTRAINT payments_package_id_fkey FOREIGN KEY (package_id) REFERENCES public.pinto_packages(id),
  CONSTRAINT payments_member_id_fkey FOREIGN KEY (member_id) REFERENCES public.members(id),
  CONSTRAINT payments_verified_by_fkey FOREIGN KEY (verified_by) REFERENCES public.erp_staff(id),
  CONSTRAINT fk_payments_package FOREIGN KEY (package_id) REFERENCES public.pinto_packages(id),
  CONSTRAINT fk_payments_member FOREIGN KEY (member_id) REFERENCES public.members(id),
  CONSTRAINT fk_payments_verified_by FOREIGN KEY (verified_by) REFERENCES public.erp_staff(id),
  CONSTRAINT fk_payments_order FOREIGN KEY (order_id) REFERENCES public.orders(order_id)
);
CREATE TABLE public.meal_deduction_logs (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  package_id uuid NOT NULL,
  order_id text NOT NULL,
  member_id uuid NOT NULL,
  meals_deducted integer NOT NULL DEFAULT 1,
  meals_before integer NOT NULL,
  meals_after integer NOT NULL,
  deducted_by uuid,
  deduction_source text DEFAULT 'system'::text,
  notes text,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT meal_deduction_logs_pkey PRIMARY KEY (id),
  CONSTRAINT fk_meal_package FOREIGN KEY (package_id) REFERENCES public.pinto_packages(id),
  CONSTRAINT fk_meal_member FOREIGN KEY (member_id) REFERENCES public.members(id),
  CONSTRAINT fk_meal_order FOREIGN KEY (order_id) REFERENCES public.orders(order_id)
);
CREATE TABLE public.notifications_log (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  member_id uuid,
  channel text NOT NULL DEFAULT 'LINE'::notification_channel_type,
  type text NOT NULL,
  reference_id text,
  template_key text,
  message_preview text,
  status text NOT NULL DEFAULT 'SENT'::text,
  error_message text,
  sent_at timestamp with time zone DEFAULT now(),
  delivered_at timestamp with time zone,
  CONSTRAINT notifications_log_pkey PRIMARY KEY (id),
  CONSTRAINT notifications_log_member_id_fkey FOREIGN KEY (member_id) REFERENCES public.members(id),
  CONSTRAINT fk_notifications_member FOREIGN KEY (member_id) REFERENCES public.members(id)
);
CREATE TABLE public.member_addresses (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  member_id uuid NOT NULL,
  label text NOT NULL DEFAULT 'บ้าน'::text,
  address_line text NOT NULL,
  district text,
  subdistrict text,
  province text DEFAULT 'เชียงราย'::text,
  postal_code text DEFAULT '57000'::text,
  lat numeric,
  lng numeric,
  delivery_notes text,
  is_default boolean DEFAULT false,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  deleted_at timestamp with time zone,
  drop_point_id uuid,
  CONSTRAINT member_addresses_pkey PRIMARY KEY (id),
  CONSTRAINT member_addresses_member_id_fkey FOREIGN KEY (member_id) REFERENCES public.members(id),
  CONSTRAINT fk_address_member FOREIGN KEY (member_id) REFERENCES public.members(id),
  CONSTRAINT fk_address_drop_point FOREIGN KEY (drop_point_id) REFERENCES public.erp_drop_points(id)
);
CREATE TABLE public.erp_kitchen_sessions (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  session_date date NOT NULL,
  menu_item_id uuid,
  planned_qty integer NOT NULL DEFAULT 0,
  actual_qty integer DEFAULT 0,
  waste_qty integer DEFAULT 0,
  notes text,
  opened_at timestamp with time zone,
  closed_at timestamp with time zone,
  opened_by uuid,
  closed_by uuid,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT erp_kitchen_sessions_pkey PRIMARY KEY (id),
  CONSTRAINT erp_kitchen_sessions_menu_item_id_fkey FOREIGN KEY (menu_item_id) REFERENCES public.menu_items(id),
  CONSTRAINT erp_kitchen_sessions_opened_by_fkey FOREIGN KEY (opened_by) REFERENCES public.erp_staff(id),
  CONSTRAINT erp_kitchen_sessions_closed_by_fkey FOREIGN KEY (closed_by) REFERENCES public.erp_staff(id),
  CONSTRAINT fk_kitchen_menu FOREIGN KEY (menu_item_id) REFERENCES public.menu_items(id),
  CONSTRAINT fk_kitchen_opened_by FOREIGN KEY (opened_by) REFERENCES public.erp_staff(id),
  CONSTRAINT fk_kitchen_closed_by FOREIGN KEY (closed_by) REFERENCES public.erp_staff(id)
);
CREATE TABLE public.orders_web (
  order_id text NOT NULL,
  phone text,
  member_id uuid,
  menu_name text,
  order_details text,
  items_total numeric DEFAULT 0,
  delivery_fee numeric DEFAULT 0,
  bundle_discount numeric DEFAULT 0,
  total_amount numeric DEFAULT 0,
  delivery_slot text,
  delivery_date timestamp with time zone,
  delivery_address text,
  delivery_lat numeric,
  delivery_lng numeric,
  customer_notes text,
  payment_status text DEFAULT 'รอตรวจสลิป'::text,
  kitchen_status text DEFAULT 'รอยืนยัน'::text,
  delivery_status text DEFAULT 'รอส่ง'::text,
  created_at timestamp with time zone DEFAULT now(),
  promotion_id uuid,
  menu_item_id uuid,
  discount_amount numeric DEFAULT 0.00,
  packaging_fee numeric DEFAULT 0.00,
  CONSTRAINT orders_web_pkey PRIMARY KEY (order_id),
  CONSTRAINT orders_web_promotion_id_fkey FOREIGN KEY (promotion_id) REFERENCES public.promotions(id),
  CONSTRAINT orders_web_menu_item_id_fkey FOREIGN KEY (menu_item_id) REFERENCES public.menu_items(id),
  CONSTRAINT fk_orders_web_member FOREIGN KEY (member_id) REFERENCES public.members(id)
);
CREATE TABLE public.shop_holidays (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  holiday_date date NOT NULL UNIQUE,
  name text NOT NULL,
  type text DEFAULT 'holiday'::text,
  is_active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT shop_holidays_pkey PRIMARY KEY (id)
);
CREATE TABLE public.order_items (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  order_id text NOT NULL,
  menu_item_id uuid,
  qty integer NOT NULL DEFAULT 1,
  unit_price numeric NOT NULL DEFAULT 0.00,
  item_type text,
  is_free_addon boolean DEFAULT false,
  addon_source text,
  CONSTRAINT order_items_pkey PRIMARY KEY (id),
  CONSTRAINT fk_order_items_menu FOREIGN KEY (menu_item_id) REFERENCES public.menu_items(id),
  CONSTRAINT fk_order_items_order FOREIGN KEY (order_id) REFERENCES public.orders(order_id)
);
CREATE TABLE public.weekly_plans (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  week_start date NOT NULL UNIQUE,
  notes text,
  status text DEFAULT 'draft'::text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT weekly_plans_pkey PRIMARY KEY (id)
);
CREATE TABLE public.erp_member_meal_schedules (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  package_id uuid,
  member_id uuid NOT NULL,
  delivery_date date NOT NULL,
  meal_type text NOT NULL,
  menu_item_id uuid,
  quantity integer DEFAULT 1,
  box_size text DEFAULT 'regular'::text,
  kitchen_status text DEFAULT 'pending'::text,
  notes text,
  created_at timestamp with time zone DEFAULT now(),
  delivery_time text,
  is_extra_order boolean DEFAULT false,
  meal_order_type text DEFAULT 'subscription'::text,
  is_compensatory boolean DEFAULT false,
  CONSTRAINT erp_member_meal_schedules_pkey PRIMARY KEY (id),
  CONSTRAINT erp_member_meal_schedules_package_id_fkey FOREIGN KEY (package_id) REFERENCES public.pinto_packages(id),
  CONSTRAINT erp_member_meal_schedules_member_id_fkey FOREIGN KEY (member_id) REFERENCES public.members(id),
  CONSTRAINT erp_member_meal_schedules_menu_item_id_fkey FOREIGN KEY (menu_item_id) REFERENCES public.menu_items(id)
);
CREATE TABLE public.erp_unit_conversions (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  item_id uuid NOT NULL,
  from_unit text NOT NULL,
  to_unit text NOT NULL,
  conversion_factor numeric NOT NULL,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT erp_unit_conversions_pkey PRIMARY KEY (id),
  CONSTRAINT fk_conversion_item FOREIGN KEY (item_id) REFERENCES public.erp_inventory_items(id)
);
CREATE TABLE public.erp_inventory_locations (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  name text NOT NULL,
  description text,
  is_active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT erp_inventory_locations_pkey PRIMARY KEY (id)
);
CREATE TABLE public.erp_inventory_adjustments (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  inventory_item_id uuid NOT NULL,
  location_id uuid,
  expected_qty numeric NOT NULL,
  actual_qty numeric NOT NULL,
  discrepancy numeric DEFAULT (actual_qty - expected_qty),
  reason text,
  adjusted_by uuid,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT erp_inventory_adjustments_pkey PRIMARY KEY (id),
  CONSTRAINT fk_adj_item FOREIGN KEY (inventory_item_id) REFERENCES public.erp_inventory_items(id),
  CONSTRAINT fk_adj_location FOREIGN KEY (location_id) REFERENCES public.erp_inventory_locations(id),
  CONSTRAINT fk_adj_staff FOREIGN KEY (adjusted_by) REFERENCES public.erp_staff(id)
);
CREATE TABLE public.erp_inventory_batches (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  inventory_item_id uuid,
  location_id uuid,
  qty numeric NOT NULL,
  unit_cost numeric NOT NULL,
  purchase_unit text,
  purchase_qty numeric,
  receipt_no text,
  supplier_id uuid,
  received_at timestamp with time zone DEFAULT now(),
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT erp_inventory_batches_pkey PRIMARY KEY (id),
  CONSTRAINT erp_inventory_batches_inventory_item_id_fkey FOREIGN KEY (inventory_item_id) REFERENCES public.erp_inventory_items(id),
  CONSTRAINT erp_inventory_batches_location_id_fkey FOREIGN KEY (location_id) REFERENCES public.erp_inventory_locations(id),
  CONSTRAINT erp_inventory_batches_supplier_id_fkey FOREIGN KEY (supplier_id) REFERENCES public.erp_suppliers(id)
);
CREATE TABLE public.erp_member_ban_logs (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  member_id uuid,
  action text NOT NULL,
  reason text,
  created_by uuid,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT erp_member_ban_logs_pkey PRIMARY KEY (id),
  CONSTRAINT erp_member_ban_logs_member_id_fkey FOREIGN KEY (member_id) REFERENCES public.members(id)
);
CREATE TABLE public.erp_blacklist (
  phone text NOT NULL,
  full_name text,
  reason text,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT erp_blacklist_pkey PRIMARY KEY (phone)
);
CREATE TABLE public.erp_kitchen_checklist (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  category text NOT NULL,
  item_name text NOT NULL,
  is_checked boolean DEFAULT false,
  updated_at timestamp with time zone DEFAULT timezone('utc'::text, now()),
  target_date date DEFAULT CURRENT_DATE,
  target_time text,
  location text,
  vendor text,
  notes text,
  CONSTRAINT erp_kitchen_checklist_pkey PRIMARY KEY (id)
);
CREATE TABLE public.erp_kitchen_checklist_master (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  category text NOT NULL,
  item_name text NOT NULL,
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()),
  vendor text,
  target_time text,
  CONSTRAINT erp_kitchen_checklist_master_pkey PRIMARY KEY (id)
);
CREATE TABLE public.erp_split_configs (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  config_name text NOT NULL,
  promotion_type text NOT NULL DEFAULT 'PINTO'::text,
  material_pct numeric NOT NULL DEFAULT 35,
  labor_pct numeric NOT NULL DEFAULT 15,
  ops_pct numeric NOT NULL DEFAULT 20,
  profit_pct numeric NOT NULL DEFAULT 30,
  is_default boolean DEFAULT false,
  is_active boolean DEFAULT true,
  notes text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT erp_split_configs_pkey PRIMARY KEY (id)
);
CREATE TABLE public.erp_fund_pools (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  pool_type text NOT NULL UNIQUE,
  display_name text NOT NULL,
  display_name_public text NOT NULL,
  current_balance numeric DEFAULT 0,
  total_in numeric DEFAULT 0,
  total_out numeric DEFAULT 0,
  target_amount numeric DEFAULT 0,
  color_code text DEFAULT '#10b981'::text,
  icon text DEFAULT '💰'::text,
  visibility text DEFAULT 'ALL'::text,
  sort_order integer DEFAULT 0,
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT erp_fund_pools_pkey PRIMARY KEY (id)
);
CREATE TABLE public.erp_revenue_buckets (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  source_type text NOT NULL,
  source_id text,
  member_id uuid,
  payment_id uuid,
  gross_amount numeric NOT NULL,
  delivery_fee numeric DEFAULT 0,
  net_amount numeric NOT NULL,
  split_config_id uuid,
  material_pct numeric DEFAULT 35,
  labor_pct numeric DEFAULT 15,
  ops_pct numeric DEFAULT 20,
  profit_pct numeric DEFAULT 30,
  material_amount numeric NOT NULL,
  labor_amount numeric NOT NULL,
  ops_amount numeric NOT NULL,
  profit_amount numeric NOT NULL,
  description text,
  status text DEFAULT 'active'::text,
  period_start date,
  period_end date,
  notes text,
  private_note text,
  created_by uuid,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT erp_revenue_buckets_pkey PRIMARY KEY (id),
  CONSTRAINT erp_revenue_buckets_member_id_fkey FOREIGN KEY (member_id) REFERENCES public.members(id),
  CONSTRAINT erp_revenue_buckets_payment_id_fkey FOREIGN KEY (payment_id) REFERENCES public.payments(id),
  CONSTRAINT erp_revenue_buckets_split_config_id_fkey FOREIGN KEY (split_config_id) REFERENCES public.erp_split_configs(id),
  CONSTRAINT erp_revenue_buckets_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.erp_staff(id)
);
CREATE TABLE public.erp_fund_transactions (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  pool_type text NOT NULL,
  direction text NOT NULL,
  amount numeric NOT NULL,
  category text,
  description text,
  private_note text,
  source_type text DEFAULT 'MANUAL'::text,
  source_id text,
  receipt_url text,
  is_personal boolean DEFAULT false,
  created_by uuid,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT erp_fund_transactions_pkey PRIMARY KEY (id),
  CONSTRAINT erp_fund_transactions_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.erp_staff(id)
);
CREATE TABLE public.erp_expense_categories (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  name text NOT NULL,
  pool_type text NOT NULL,
  icon text DEFAULT '📦'::text,
  color text DEFAULT '#64748b'::text,
  visibility text DEFAULT 'ALL'::text,
  is_personal boolean DEFAULT false,
  sort_order integer DEFAULT 0,
  is_active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT erp_expense_categories_pkey PRIMARY KEY (id)
);
CREATE TABLE public.erp_settings (
  key text NOT NULL,
  value jsonb NOT NULL,
  description text,
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT erp_settings_pkey PRIMARY KEY (key)
);
CREATE TABLE public.erp_shipping_discounts (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  min_order numeric NOT NULL,
  discount_amount numeric NOT NULL,
  label text,
  is_active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT erp_shipping_discounts_pkey PRIMARY KEY (id)
);
CREATE TABLE public.menu_cycle_templates (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  week_number integer NOT NULL,
  day_of_week integer NOT NULL,
  meal_slot integer NOT NULL,
  category text,
  protein text,
  menu_name text NOT NULL,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT menu_cycle_templates_pkey PRIMARY KEY (id)
);
CREATE TABLE public.erp_recipe_steps (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  menu_item_id uuid,
  step_number integer NOT NULL,
  instruction text NOT NULL,
  time_minutes integer DEFAULT 0,
  image_url text,
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()),
  updated_at timestamp with time zone DEFAULT timezone('utc'::text, now()),
  CONSTRAINT erp_recipe_steps_pkey PRIMARY KEY (id),
  CONSTRAINT erp_recipe_steps_menu_item_id_fkey FOREIGN KEY (menu_item_id) REFERENCES public.menu_items(id)
);
CREATE TABLE public.erp_units (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  name character varying NOT NULL UNIQUE,
  abbreviation character varying,
  category character varying,
  is_base_unit boolean DEFAULT false,
  conversion_factor numeric DEFAULT 1,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT erp_units_pkey PRIMARY KEY (id)
);
CREATE TABLE public.erp_tenants (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  tenant_code text NOT NULL UNIQUE,
  tenant_name text NOT NULL,
  business_type text DEFAULT 'meal_prep'::text,
  owner_name text,
  owner_phone text,
  owner_email text,
  logo_url text,
  address text,
  province text,
  postal_code text,
  lat numeric,
  lng numeric,
  tax_id text,
  branch_name text DEFAULT 'สำนักงานใหญ่'::text,
  status text DEFAULT 'trial'::text,
  trial_ends_at timestamp with time zone DEFAULT (now() + '30 days'::interval),
  subscription_tier text DEFAULT 'starter'::text,
  timezone text DEFAULT 'Asia/Bangkok'::text,
  currency text DEFAULT 'THB'::text,
  language text DEFAULT 'th'::text,
  settings jsonb DEFAULT '{}'::jsonb,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  deleted_at timestamp with time zone,
  CONSTRAINT erp_tenants_pkey PRIMARY KEY (id)
);
CREATE TABLE public.erp_tenant_subscriptions (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  tenant_id uuid NOT NULL,
  plan_name text NOT NULL,
  billing_cycle text DEFAULT 'monthly'::text,
  price_per_cycle numeric NOT NULL DEFAULT 990.00,
  max_users integer DEFAULT 3,
  max_menu_items integer DEFAULT 50,
  max_members integer DEFAULT 200,
  max_orders_per_month integer DEFAULT 1000,
  features_enabled jsonb DEFAULT '["kds", "menu", "members", "pinto"]'::jsonb,
  start_date date NOT NULL DEFAULT CURRENT_DATE,
  end_date date,
  next_billing_date date,
  status text DEFAULT 'active'::text,
  cancelled_at timestamp with time zone,
  cancelled_reason text,
  last_payment_amount numeric DEFAULT 0.00,
  last_payment_date timestamp with time zone,
  total_paid numeric DEFAULT 0.00,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT erp_tenant_subscriptions_pkey PRIMARY KEY (id),
  CONSTRAINT erp_ts_tenant_fkey FOREIGN KEY (tenant_id) REFERENCES public.erp_tenants(id)
);
CREATE TABLE public.erp_tenant_users (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  tenant_id uuid NOT NULL,
  auth_user_id uuid,
  staff_id uuid,
  full_name text NOT NULL,
  email text,
  phone text,
  role text DEFAULT 'staff'::text,
  permissions jsonb DEFAULT '[]'::jsonb,
  is_active boolean DEFAULT true,
  last_login_at timestamp with time zone,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT erp_tenant_users_pkey PRIMARY KEY (id),
  CONSTRAINT erp_tu_tenant_fkey FOREIGN KEY (tenant_id) REFERENCES public.erp_tenants(id),
  CONSTRAINT erp_tu_staff_fkey FOREIGN KEY (staff_id) REFERENCES public.erp_staff(id)
);
CREATE TABLE public.erp_tenant_configs (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  tenant_id uuid NOT NULL,
  config_key text NOT NULL,
  config_value jsonb NOT NULL DEFAULT '{}'::jsonb,
  description text,
  is_sensitive boolean DEFAULT false,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT erp_tenant_configs_pkey PRIMARY KEY (id),
  CONSTRAINT erp_tc_tenant_fkey FOREIGN KEY (tenant_id) REFERENCES public.erp_tenants(id)
);
CREATE TABLE public.erp_production_orders (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  tenant_id uuid NOT NULL DEFAULT '00000000-0000-0000-0000-000000000001'::uuid,
  production_date date NOT NULL DEFAULT CURRENT_DATE,
  shift text DEFAULT 'morning'::text,
  status text NOT NULL DEFAULT 'draft'::text CHECK (status = ANY (ARRAY['draft'::text, 'in_progress'::text, 'completed'::text, 'cancelled'::text])),
  total_items integer DEFAULT 0,
  total_produced integer DEFAULT 0,
  total_waste integer DEFAULT 0,
  stock_deducted boolean DEFAULT false,
  notes text,
  created_by uuid,
  approved_by uuid,
  started_at timestamp with time zone,
  completed_at timestamp with time zone,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT erp_production_orders_pkey PRIMARY KEY (id),
  CONSTRAINT erp_po_tenant_fkey FOREIGN KEY (tenant_id) REFERENCES public.erp_tenants(id),
  CONSTRAINT erp_po_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.erp_staff(id),
  CONSTRAINT erp_po_approved_by_fkey FOREIGN KEY (approved_by) REFERENCES public.erp_staff(id)
);
CREATE TABLE public.erp_production_order_items (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  tenant_id uuid NOT NULL DEFAULT '00000000-0000-0000-0000-000000000001'::uuid,
  production_order_id uuid NOT NULL,
  menu_item_id uuid NOT NULL,
  planned_qty integer NOT NULL DEFAULT 0,
  actual_qty integer DEFAULT 0,
  waste_qty integer DEFAULT 0,
  yield_percentage numeric DEFAULT 100.0,
  notes text,
  status text DEFAULT 'pending'::text,
  started_at timestamp with time zone,
  completed_at timestamp with time zone,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT erp_production_order_items_pkey PRIMARY KEY (id),
  CONSTRAINT erp_poi_tenant_fkey FOREIGN KEY (tenant_id) REFERENCES public.erp_tenants(id),
  CONSTRAINT erp_poi_order_fkey FOREIGN KEY (production_order_id) REFERENCES public.erp_production_orders(id),
  CONSTRAINT erp_poi_menu_fkey FOREIGN KEY (menu_item_id) REFERENCES public.menu_items(id)
);
CREATE TABLE public.erp_stock_deductions (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  tenant_id uuid NOT NULL DEFAULT '00000000-0000-0000-0000-000000000001'::uuid,
  production_order_id uuid NOT NULL,
  production_order_item_id uuid,
  inventory_item_id uuid NOT NULL,
  recipe_id uuid,
  qty_deducted numeric NOT NULL,
  unit text NOT NULL,
  unit_cost_at_deduction numeric DEFAULT 0.00,
  total_cost numeric DEFAULT 0.00,
  deducted_by uuid,
  deducted_at timestamp with time zone DEFAULT now(),
  reversed boolean DEFAULT false,
  reversed_at timestamp with time zone,
  reversed_by uuid,
  notes text,
  CONSTRAINT erp_stock_deductions_pkey PRIMARY KEY (id),
  CONSTRAINT erp_sd_tenant_fkey FOREIGN KEY (tenant_id) REFERENCES public.erp_tenants(id),
  CONSTRAINT erp_sd_order_fkey FOREIGN KEY (production_order_id) REFERENCES public.erp_production_orders(id),
  CONSTRAINT erp_sd_poi_fkey FOREIGN KEY (production_order_item_id) REFERENCES public.erp_production_order_items(id),
  CONSTRAINT erp_sd_item_fkey FOREIGN KEY (inventory_item_id) REFERENCES public.erp_inventory_items(id),
  CONSTRAINT erp_sd_recipe_fkey FOREIGN KEY (recipe_id) REFERENCES public.erp_recipes(id),
  CONSTRAINT erp_sd_deducted_by_fkey FOREIGN KEY (deducted_by) REFERENCES public.erp_staff(id)
);
CREATE TABLE public.erp_food_safety_logs (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  tenant_id uuid NOT NULL DEFAULT '00000000-0000-0000-0000-000000000001'::uuid,
  log_date date NOT NULL DEFAULT CURRENT_DATE,
  log_time time without time zone NOT NULL DEFAULT CURRENT_TIME,
  category text NOT NULL,
  location text,
  check_item text NOT NULL,
  reading_value numeric,
  reading_unit text DEFAULT '°C'::text,
  min_acceptable numeric,
  max_acceptable numeric,
  is_pass boolean DEFAULT true,
  corrective_action text,
  photo_url text,
  checked_by uuid NOT NULL,
  verified_by uuid,
  notes text,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT erp_food_safety_logs_pkey PRIMARY KEY (id),
  CONSTRAINT erp_fsl_tenant_fkey FOREIGN KEY (tenant_id) REFERENCES public.erp_tenants(id),
  CONSTRAINT erp_fsl_checked_by_fkey FOREIGN KEY (checked_by) REFERENCES public.erp_staff(id),
  CONSTRAINT erp_fsl_verified_by_fkey FOREIGN KEY (verified_by) REFERENCES public.erp_staff(id)
);
CREATE TABLE public.erp_demand_forecasts (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  tenant_id uuid NOT NULL DEFAULT '00000000-0000-0000-0000-000000000001'::uuid,
  forecast_date date NOT NULL,
  menu_item_id uuid,
  inventory_item_id uuid,
  forecast_qty numeric NOT NULL DEFAULT 0,
  confidence_score numeric DEFAULT 0.5,
  source text DEFAULT 'system'::text,
  actual_qty numeric,
  variance numeric,
  notes text,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT erp_demand_forecasts_pkey PRIMARY KEY (id),
  CONSTRAINT erp_df_tenant_fkey FOREIGN KEY (tenant_id) REFERENCES public.erp_tenants(id),
  CONSTRAINT erp_df_menu_fkey FOREIGN KEY (menu_item_id) REFERENCES public.menu_items(id),
  CONSTRAINT erp_df_item_fkey FOREIGN KEY (inventory_item_id) REFERENCES public.erp_inventory_items(id)
);
CREATE TABLE public.erp_purchase_orders (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  tenant_id uuid NOT NULL DEFAULT '00000000-0000-0000-0000-000000000001'::uuid,
  po_number text NOT NULL,
  supplier_id uuid NOT NULL,
  status text NOT NULL DEFAULT 'draft'::text,
  order_date date NOT NULL DEFAULT CURRENT_DATE,
  expected_delivery_date date,
  actual_delivery_date date,
  subtotal numeric DEFAULT 0.00,
  discount_amount numeric DEFAULT 0.00,
  vat_amount numeric DEFAULT 0.00,
  total_amount numeric DEFAULT 0.00,
  payment_terms text DEFAULT 'COD'::text,
  payment_status text DEFAULT 'unpaid'::text,
  paid_amount numeric DEFAULT 0.00,
  delivery_address text,
  notes text,
  internal_notes text,
  created_by uuid,
  approved_by uuid,
  approved_at timestamp with time zone,
  cancelled_by uuid,
  cancelled_at timestamp with time zone,
  cancelled_reason text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT erp_purchase_orders_pkey PRIMARY KEY (id),
  CONSTRAINT erp_puro_tenant_fkey FOREIGN KEY (tenant_id) REFERENCES public.erp_tenants(id),
  CONSTRAINT erp_puro_supplier_fkey FOREIGN KEY (supplier_id) REFERENCES public.erp_suppliers(id),
  CONSTRAINT erp_puro_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.erp_staff(id),
  CONSTRAINT erp_puro_approved_by_fkey FOREIGN KEY (approved_by) REFERENCES public.erp_staff(id)
);
CREATE TABLE public.erp_purchase_order_items (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  tenant_id uuid NOT NULL DEFAULT '00000000-0000-0000-0000-000000000001'::uuid,
  purchase_order_id uuid NOT NULL,
  inventory_item_id uuid NOT NULL,
  description text,
  quantity numeric NOT NULL,
  unit text NOT NULL,
  unit_price numeric NOT NULL DEFAULT 0.00,
  discount_pct numeric DEFAULT 0.00,
  amount numeric NOT NULL DEFAULT 0.00,
  received_qty numeric DEFAULT 0,
  remaining_qty numeric DEFAULT 0,
  notes text,
  CONSTRAINT erp_purchase_order_items_pkey PRIMARY KEY (id),
  CONSTRAINT erp_puoi_tenant_fkey FOREIGN KEY (tenant_id) REFERENCES public.erp_tenants(id),
  CONSTRAINT erp_puoi_po_fkey FOREIGN KEY (purchase_order_id) REFERENCES public.erp_purchase_orders(id),
  CONSTRAINT erp_puoi_item_fkey FOREIGN KEY (inventory_item_id) REFERENCES public.erp_inventory_items(id)
);
CREATE TABLE public.erp_goods_receipts (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  tenant_id uuid NOT NULL DEFAULT '00000000-0000-0000-0000-000000000001'::uuid,
  gr_number text NOT NULL,
  purchase_order_id uuid,
  supplier_id uuid NOT NULL,
  receipt_date date NOT NULL DEFAULT CURRENT_DATE,
  status text DEFAULT 'draft'::text,
  total_amount numeric DEFAULT 0.00,
  invoice_number text,
  received_by uuid NOT NULL,
  confirmed_by uuid,
  confirmed_at timestamp with time zone,
  notes text,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT erp_goods_receipts_pkey PRIMARY KEY (id),
  CONSTRAINT erp_gr_tenant_fkey FOREIGN KEY (tenant_id) REFERENCES public.erp_tenants(id),
  CONSTRAINT erp_gr_po_fkey FOREIGN KEY (purchase_order_id) REFERENCES public.erp_purchase_orders(id),
  CONSTRAINT erp_gr_supplier_fkey FOREIGN KEY (supplier_id) REFERENCES public.erp_suppliers(id),
  CONSTRAINT erp_gr_received_by_fkey FOREIGN KEY (received_by) REFERENCES public.erp_staff(id)
);
CREATE TABLE public.erp_goods_receipt_items (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  tenant_id uuid NOT NULL DEFAULT '00000000-0000-0000-0000-000000000001'::uuid,
  goods_receipt_id uuid NOT NULL,
  inventory_item_id uuid NOT NULL,
  po_item_id uuid,
  received_qty numeric NOT NULL,
  unit text NOT NULL,
  unit_cost numeric NOT NULL DEFAULT 0.00,
  total_cost numeric NOT NULL DEFAULT 0.00,
  expiry_date date,
  batch_number text,
  location_id uuid,
  quality_status text DEFAULT 'accepted'::text,
  rejection_reason text,
  notes text,
  CONSTRAINT erp_goods_receipt_items_pkey PRIMARY KEY (id),
  CONSTRAINT erp_gri_tenant_fkey FOREIGN KEY (tenant_id) REFERENCES public.erp_tenants(id),
  CONSTRAINT erp_gri_gr_fkey FOREIGN KEY (goods_receipt_id) REFERENCES public.erp_goods_receipts(id),
  CONSTRAINT erp_gri_item_fkey FOREIGN KEY (inventory_item_id) REFERENCES public.erp_inventory_items(id),
  CONSTRAINT erp_gri_po_item_fkey FOREIGN KEY (po_item_id) REFERENCES public.erp_purchase_order_items(id),
  CONSTRAINT erp_gri_location_fkey FOREIGN KEY (location_id) REFERENCES public.erp_inventory_locations(id)
);
CREATE TABLE public.erp_supplier_price_lists (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  tenant_id uuid NOT NULL DEFAULT '00000000-0000-0000-0000-000000000001'::uuid,
  supplier_id uuid NOT NULL,
  inventory_item_id uuid NOT NULL,
  unit text NOT NULL,
  unit_price numeric NOT NULL DEFAULT 0.00,
  min_order_qty numeric DEFAULT 0,
  lead_time_days integer DEFAULT 1,
  valid_from date DEFAULT CURRENT_DATE,
  valid_until date,
  is_preferred boolean DEFAULT false,
  last_purchase_price numeric DEFAULT 0.00,
  last_purchase_date date,
  avg_price_3m numeric DEFAULT 0.00,
  notes text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT erp_supplier_price_lists_pkey PRIMARY KEY (id),
  CONSTRAINT erp_spl_tenant_fkey FOREIGN KEY (tenant_id) REFERENCES public.erp_tenants(id),
  CONSTRAINT erp_spl_supplier_fkey FOREIGN KEY (supplier_id) REFERENCES public.erp_suppliers(id),
  CONSTRAINT erp_spl_item_fkey FOREIGN KEY (inventory_item_id) REFERENCES public.erp_inventory_items(id)
);
CREATE TABLE public.erp_bank_accounts (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  tenant_id uuid NOT NULL DEFAULT '00000000-0000-0000-0000-000000000001'::uuid,
  account_name text NOT NULL,
  bank_name text NOT NULL,
  account_number text NOT NULL,
  account_type text DEFAULT 'savings'::text,
  current_balance numeric DEFAULT 0.00,
  is_primary boolean DEFAULT false,
  is_active boolean DEFAULT true,
  holder_name text,
  branch text,
  promptpay_id text,
  qr_code_url text,
  notes text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT erp_bank_accounts_pkey PRIMARY KEY (id),
  CONSTRAINT erp_ba_tenant_fkey FOREIGN KEY (tenant_id) REFERENCES public.erp_tenants(id)
);
CREATE TABLE public.erp_invoices (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  tenant_id uuid NOT NULL DEFAULT '00000000-0000-0000-0000-000000000001'::uuid,
  invoice_number text NOT NULL,
  invoice_type text NOT NULL DEFAULT 'receipt'::text,
  status text NOT NULL DEFAULT 'draft'::text,
  member_id uuid,
  customer_name text NOT NULL,
  customer_address text,
  customer_tax_id text,
  customer_branch text DEFAULT 'สำนักงานใหญ่'::text,
  customer_phone text,
  customer_email text,
  subtotal numeric NOT NULL DEFAULT 0.00,
  discount_amount numeric DEFAULT 0.00,
  amount_before_vat numeric DEFAULT 0.00,
  vat_rate numeric DEFAULT 7.0,
  vat_amount numeric DEFAULT 0.00,
  withholding_tax_rate numeric DEFAULT 0.0,
  withholding_tax_amount numeric DEFAULT 0.00,
  total_amount numeric NOT NULL DEFAULT 0.00,
  payment_method text,
  payment_ref text,
  paid_at timestamp with time zone,
  seller_name text DEFAULT 'Clean Food CR'::text,
  seller_address text,
  seller_tax_id text,
  seller_branch text DEFAULT 'สำนักงานใหญ่'::text,
  issue_date date NOT NULL DEFAULT CURRENT_DATE,
  due_date date,
  notes text,
  internal_notes text,
  pdf_url text,
  created_by uuid,
  voided_by uuid,
  voided_reason text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT erp_invoices_pkey PRIMARY KEY (id),
  CONSTRAINT erp_inv_tenant_fkey FOREIGN KEY (tenant_id) REFERENCES public.erp_tenants(id),
  CONSTRAINT erp_inv_member_fkey FOREIGN KEY (member_id) REFERENCES public.members(id),
  CONSTRAINT erp_inv_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.erp_staff(id)
);
CREATE TABLE public.erp_invoice_items (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  tenant_id uuid NOT NULL DEFAULT '00000000-0000-0000-0000-000000000001'::uuid,
  invoice_id uuid NOT NULL,
  description text NOT NULL,
  quantity numeric NOT NULL DEFAULT 1,
  unit text DEFAULT 'ชิ้น'::text,
  unit_price numeric NOT NULL DEFAULT 0.00,
  discount numeric DEFAULT 0.00,
  amount numeric NOT NULL DEFAULT 0.00,
  order_id text,
  package_id uuid,
  menu_item_id uuid,
  sort_order integer DEFAULT 0,
  CONSTRAINT erp_invoice_items_pkey PRIMARY KEY (id),
  CONSTRAINT erp_invi_tenant_fkey FOREIGN KEY (tenant_id) REFERENCES public.erp_tenants(id),
  CONSTRAINT erp_invi_invoice_fkey FOREIGN KEY (invoice_id) REFERENCES public.erp_invoices(id),
  CONSTRAINT erp_invi_menu_fkey FOREIGN KEY (menu_item_id) REFERENCES public.menu_items(id)
);
CREATE TABLE public.erp_pl_snapshots (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  tenant_id uuid NOT NULL DEFAULT '00000000-0000-0000-0000-000000000001'::uuid,
  period_year integer NOT NULL,
  period_month integer NOT NULL,
  period_type text DEFAULT 'monthly'::text,
  revenue_subscription numeric DEFAULT 0.00,
  revenue_retail numeric DEFAULT 0.00,
  revenue_addon numeric DEFAULT 0.00,
  revenue_delivery_fee numeric DEFAULT 0.00,
  revenue_other numeric DEFAULT 0.00,
  total_revenue numeric DEFAULT 0.00,
  cogs_material numeric DEFAULT 0.00,
  cogs_packaging numeric DEFAULT 0.00,
  cogs_other numeric DEFAULT 0.00,
  total_cogs numeric DEFAULT 0.00,
  gross_profit numeric DEFAULT 0.00,
  gross_margin_pct numeric DEFAULT 0.00,
  opex_labor numeric DEFAULT 0.00,
  opex_delivery numeric DEFAULT 0.00,
  opex_rent numeric DEFAULT 0.00,
  opex_utilities numeric DEFAULT 0.00,
  opex_marketing numeric DEFAULT 0.00,
  opex_other numeric DEFAULT 0.00,
  total_opex numeric DEFAULT 0.00,
  net_income numeric DEFAULT 0.00,
  net_margin_pct numeric DEFAULT 0.00,
  is_finalized boolean DEFAULT false,
  finalized_by uuid,
  finalized_at timestamp with time zone,
  notes text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT erp_pl_snapshots_pkey PRIMARY KEY (id),
  CONSTRAINT erp_pl_tenant_fkey FOREIGN KEY (tenant_id) REFERENCES public.erp_tenants(id),
  CONSTRAINT erp_pl_finalized_by_fkey FOREIGN KEY (finalized_by) REFERENCES public.erp_staff(id)
);
CREATE TABLE public.erp_cash_reconciliations (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  tenant_id uuid NOT NULL DEFAULT '00000000-0000-0000-0000-000000000001'::uuid,
  reconciliation_date date NOT NULL DEFAULT CURRENT_DATE,
  pool_type text NOT NULL,
  opening_balance numeric NOT NULL DEFAULT 0.00,
  total_income numeric DEFAULT 0.00,
  total_expense numeric DEFAULT 0.00,
  expected_balance numeric DEFAULT 0.00,
  actual_balance numeric NOT NULL DEFAULT 0.00,
  variance numeric DEFAULT 0.00,
  variance_reason text,
  status text DEFAULT 'pending'::text,
  counted_by uuid NOT NULL,
  approved_by uuid,
  approved_at timestamp with time zone,
  notes text,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT erp_cash_reconciliations_pkey PRIMARY KEY (id),
  CONSTRAINT erp_cr_tenant_fkey FOREIGN KEY (tenant_id) REFERENCES public.erp_tenants(id),
  CONSTRAINT erp_cr_counted_by_fkey FOREIGN KEY (counted_by) REFERENCES public.erp_staff(id),
  CONSTRAINT erp_cr_approved_by_fkey FOREIGN KEY (approved_by) REFERENCES public.erp_staff(id)
);
CREATE TABLE public.erp_crm_interactions (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  tenant_id uuid NOT NULL DEFAULT '00000000-0000-0000-0000-000000000001'::uuid,
  member_id uuid NOT NULL,
  interaction_type text NOT NULL,
  direction text DEFAULT 'outbound'::text,
  subject text,
  content text,
  sentiment text,
  follow_up_required boolean DEFAULT false,
  follow_up_date date,
  follow_up_done boolean DEFAULT false,
  handled_by uuid,
  notes text,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT erp_crm_interactions_pkey PRIMARY KEY (id),
  CONSTRAINT erp_ci_tenant_fkey FOREIGN KEY (tenant_id) REFERENCES public.erp_tenants(id),
  CONSTRAINT erp_ci_member_fkey FOREIGN KEY (member_id) REFERENCES public.members(id),
  CONSTRAINT erp_ci_handled_by_fkey FOREIGN KEY (handled_by) REFERENCES public.erp_staff(id)
);
CREATE TABLE public.erp_crm_campaigns (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  tenant_id uuid NOT NULL DEFAULT '00000000-0000-0000-0000-000000000001'::uuid,
  campaign_name text NOT NULL,
  campaign_type text NOT NULL,
  status text DEFAULT 'draft'::text,
  target_segment text,
  message_template text,
  promotion_id uuid,
  scheduled_at timestamp with time zone,
  started_at timestamp with time zone,
  completed_at timestamp with time zone,
  total_targets integer DEFAULT 0,
  total_sent integer DEFAULT 0,
  total_opened integer DEFAULT 0,
  total_converted integer DEFAULT 0,
  budget numeric DEFAULT 0.00,
  actual_cost numeric DEFAULT 0.00,
  roi numeric DEFAULT 0.00,
  notes text,
  created_by uuid,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT erp_crm_campaigns_pkey PRIMARY KEY (id),
  CONSTRAINT erp_cc_tenant_fkey FOREIGN KEY (tenant_id) REFERENCES public.erp_tenants(id),
  CONSTRAINT erp_cc_promotion_fkey FOREIGN KEY (promotion_id) REFERENCES public.promotions(id),
  CONSTRAINT erp_cc_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.erp_staff(id)
);
CREATE TABLE public.erp_crm_campaign_members (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  tenant_id uuid NOT NULL DEFAULT '00000000-0000-0000-0000-000000000001'::uuid,
  campaign_id uuid NOT NULL,
  member_id uuid NOT NULL,
  status text DEFAULT 'pending'::text,
  sent_at timestamp with time zone,
  opened_at timestamp with time zone,
  converted_at timestamp with time zone,
  conversion_value numeric DEFAULT 0.00,
  CONSTRAINT erp_crm_campaign_members_pkey PRIMARY KEY (id),
  CONSTRAINT erp_ccm_tenant_fkey FOREIGN KEY (tenant_id) REFERENCES public.erp_tenants(id),
  CONSTRAINT erp_ccm_campaign_fkey FOREIGN KEY (campaign_id) REFERENCES public.erp_crm_campaigns(id),
  CONSTRAINT erp_ccm_member_fkey FOREIGN KEY (member_id) REFERENCES public.members(id)
);
CREATE TABLE public.erp_churn_scores (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  tenant_id uuid NOT NULL DEFAULT '00000000-0000-0000-0000-000000000001'::uuid,
  member_id uuid NOT NULL,
  score numeric NOT NULL DEFAULT 0.0,
  risk_level text DEFAULT 'low'::text,
  days_since_last_order integer DEFAULT 0,
  order_frequency_30d integer DEFAULT 0,
  order_frequency_90d integer DEFAULT 0,
  avg_order_value numeric DEFAULT 0.00,
  streak_current integer DEFAULT 0,
  streak_longest integer DEFAULT 0,
  total_lifetime_value numeric DEFAULT 0.00,
  package_status text,
  last_interaction_date date,
  satisfaction_avg numeric DEFAULT 0.0,
  calculated_at timestamp with time zone DEFAULT now(),
  model_version text DEFAULT 'v1'::text,
  CONSTRAINT erp_churn_scores_pkey PRIMARY KEY (id),
  CONSTRAINT erp_cs_tenant_fkey FOREIGN KEY (tenant_id) REFERENCES public.erp_tenants(id),
  CONSTRAINT erp_cs_member_fkey FOREIGN KEY (member_id) REFERENCES public.members(id)
);
CREATE TABLE public.erp_menu_preferences (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  tenant_id uuid NOT NULL DEFAULT '00000000-0000-0000-0000-000000000001'::uuid,
  member_id uuid NOT NULL,
  preference_type text NOT NULL,
  preference_value text NOT NULL,
  preference_level text DEFAULT 'like'::text,
  source text DEFAULT 'auto'::text,
  confidence numeric DEFAULT 0.5,
  order_count integer DEFAULT 0,
  last_ordered_at timestamp with time zone,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT erp_menu_preferences_pkey PRIMARY KEY (id),
  CONSTRAINT erp_mp_tenant_fkey FOREIGN KEY (tenant_id) REFERENCES public.erp_tenants(id),
  CONSTRAINT erp_mp_member_fkey FOREIGN KEY (member_id) REFERENCES public.members(id)
);
CREATE TABLE public.erp_delivery_routes (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  tenant_id uuid NOT NULL DEFAULT '00000000-0000-0000-0000-000000000001'::uuid,
  route_date date NOT NULL DEFAULT CURRENT_DATE,
  shift text DEFAULT 'morning'::text,
  rider_id uuid NOT NULL,
  status text DEFAULT 'planned'::text,
  total_stops integer DEFAULT 0,
  total_distance_km numeric DEFAULT 0.00,
  estimated_duration_minutes integer DEFAULT 0,
  actual_duration_minutes integer,
  optimization_method text DEFAULT 'nearest_neighbor'::text,
  optimization_score numeric DEFAULT 0.0,
  departed_at timestamp with time zone,
  completed_at timestamp with time zone,
  notes text,
  created_by uuid,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT erp_delivery_routes_pkey PRIMARY KEY (id),
  CONSTRAINT erp_dr_tenant_fkey FOREIGN KEY (tenant_id) REFERENCES public.erp_tenants(id),
  CONSTRAINT erp_dr_rider_fkey FOREIGN KEY (rider_id) REFERENCES public.erp_staff(id),
  CONSTRAINT erp_dr_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.erp_staff(id)
);
CREATE TABLE public.erp_delivery_route_stops (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  tenant_id uuid NOT NULL DEFAULT '00000000-0000-0000-0000-000000000001'::uuid,
  route_id uuid NOT NULL,
  stop_order integer NOT NULL,
  delivery_id uuid,
  member_id uuid,
  address text,
  lat numeric,
  lng numeric,
  distance_from_prev_km numeric DEFAULT 0.00,
  estimated_arrival timestamp with time zone,
  actual_arrival timestamp with time zone,
  status text DEFAULT 'pending'::text,
  delivery_proof_url text,
  notes text,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT erp_delivery_route_stops_pkey PRIMARY KEY (id),
  CONSTRAINT erp_drs_tenant_fkey FOREIGN KEY (tenant_id) REFERENCES public.erp_tenants(id),
  CONSTRAINT erp_drs_route_fkey FOREIGN KEY (route_id) REFERENCES public.erp_delivery_routes(id),
  CONSTRAINT erp_drs_delivery_fkey FOREIGN KEY (delivery_id) REFERENCES public.erp_deliveries(id),
  CONSTRAINT erp_drs_member_fkey FOREIGN KEY (member_id) REFERENCES public.members(id)
);
CREATE TABLE public.erp_rider_gps_logs (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  tenant_id uuid NOT NULL DEFAULT '00000000-0000-0000-0000-000000000001'::uuid,
  rider_id uuid NOT NULL,
  route_id uuid,
  lat numeric NOT NULL,
  lng numeric NOT NULL,
  speed_kmh numeric DEFAULT 0.0,
  heading numeric DEFAULT 0.0,
  accuracy_meters numeric DEFAULT 0.0,
  battery_level integer,
  recorded_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT erp_rider_gps_logs_pkey PRIMARY KEY (id),
  CONSTRAINT erp_gps_tenant_fkey FOREIGN KEY (tenant_id) REFERENCES public.erp_tenants(id),
  CONSTRAINT erp_gps_rider_fkey FOREIGN KEY (rider_id) REFERENCES public.erp_staff(id),
  CONSTRAINT erp_gps_route_fkey FOREIGN KEY (route_id) REFERENCES public.erp_delivery_routes(id)
);
CREATE TABLE public.erp_rider_performance (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  tenant_id uuid NOT NULL DEFAULT '00000000-0000-0000-0000-000000000001'::uuid,
  rider_id uuid NOT NULL,
  period_date date NOT NULL,
  total_deliveries integer DEFAULT 0,
  on_time_deliveries integer DEFAULT 0,
  late_deliveries integer DEFAULT 0,
  failed_deliveries integer DEFAULT 0,
  on_time_pct numeric DEFAULT 0.0,
  total_distance_km numeric DEFAULT 0.00,
  total_ratings integer DEFAULT 0,
  avg_rating numeric DEFAULT 0.0,
  complaints integer DEFAULT 0,
  total_earnings numeric DEFAULT 0.00,
  fuel_claimed numeric DEFAULT 0.00,
  performance_score numeric DEFAULT 0.0,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT erp_rider_performance_pkey PRIMARY KEY (id),
  CONSTRAINT erp_rp_tenant_fkey FOREIGN KEY (tenant_id) REFERENCES public.erp_tenants(id),
  CONSTRAINT erp_rp_rider_fkey FOREIGN KEY (rider_id) REFERENCES public.erp_staff(id)
);
CREATE TABLE public.erp_fuel_claims (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  tenant_id uuid NOT NULL DEFAULT '00000000-0000-0000-0000-000000000001'::uuid,
  rider_id uuid NOT NULL,
  claim_date date NOT NULL DEFAULT CURRENT_DATE,
  route_id uuid,
  distance_km numeric NOT NULL,
  distance_source text DEFAULT 'gps'::text,
  rate_per_km numeric NOT NULL DEFAULT 3.00,
  vehicle_type text DEFAULT 'motorcycle'::text,
  fuel_amount numeric NOT NULL DEFAULT 0.00,
  surcharge numeric DEFAULT 0.00,
  total_claim numeric NOT NULL DEFAULT 0.00,
  status text DEFAULT 'pending'::text,
  approved_by uuid,
  approved_at timestamp with time zone,
  rejected_reason text,
  paid_at timestamp with time zone,
  receipt_url text,
  notes text,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT erp_fuel_claims_pkey PRIMARY KEY (id),
  CONSTRAINT erp_fc_tenant_fkey FOREIGN KEY (tenant_id) REFERENCES public.erp_tenants(id),
  CONSTRAINT erp_fc_rider_fkey FOREIGN KEY (rider_id) REFERENCES public.erp_staff(id),
  CONSTRAINT erp_fc_route_fkey FOREIGN KEY (route_id) REFERENCES public.erp_delivery_routes(id),
  CONSTRAINT erp_fc_approved_by_fkey FOREIGN KEY (approved_by) REFERENCES public.erp_staff(id)
);
CREATE TABLE public.erp_drop_points (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  tenant_id uuid NOT NULL DEFAULT '00000000-0000-0000-0000-000000000001'::uuid,
  name text NOT NULL,
  short_code text,
  address_line text,
  lat numeric,
  lng numeric,
  radius_km numeric DEFAULT 0.5,
  contact_name text,
  contact_phone text,
  delivery_instructions text,
  avg_orders_per_day numeric DEFAULT 0,
  is_active boolean DEFAULT true,
  notes text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT erp_drop_points_pkey PRIMARY KEY (id),
  CONSTRAINT erp_dp_tenant_fkey FOREIGN KEY (tenant_id) REFERENCES public.erp_tenants(id)
);
CREATE TABLE public.erp_group_orders (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  tenant_id uuid NOT NULL DEFAULT '00000000-0000-0000-0000-000000000001'::uuid,
  group_code text,
  drop_point_id uuid NOT NULL,
  promotion_id uuid,
  order_date date NOT NULL DEFAULT CURRENT_DATE,
  total_boxes integer NOT NULL DEFAULT 0,
  min_boxes_required integer DEFAULT 3,
  is_qualified boolean DEFAULT false,
  free_addon_type text,
  free_addon_value_per_box numeric DEFAULT 20.00,
  total_addon_cost numeric DEFAULT 0.00,
  status text DEFAULT 'pending'::text,
  created_by uuid,
  notes text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT erp_group_orders_pkey PRIMARY KEY (id),
  CONSTRAINT erp_go_tenant_fkey FOREIGN KEY (tenant_id) REFERENCES public.erp_tenants(id),
  CONSTRAINT erp_go_drop_point_fkey FOREIGN KEY (drop_point_id) REFERENCES public.erp_drop_points(id),
  CONSTRAINT erp_go_promotion_fkey FOREIGN KEY (promotion_id) REFERENCES public.promotions(id),
  CONSTRAINT erp_go_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.erp_staff(id)
);
CREATE TABLE public.erp_buddy_groups (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  tenant_id uuid NOT NULL DEFAULT '00000000-0000-0000-0000-000000000001'::uuid,
  group_name text,
  group_code text,
  drop_point_id uuid,
  promotion_id uuid,
  min_members integer DEFAULT 2,
  current_members integer DEFAULT 0,
  bonus_meals_per_person integer DEFAULT 2,
  is_qualified boolean DEFAULT false,
  status text DEFAULT 'forming'::text,
  created_by uuid,
  notes text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT erp_buddy_groups_pkey PRIMARY KEY (id),
  CONSTRAINT erp_bg_tenant_fkey FOREIGN KEY (tenant_id) REFERENCES public.erp_tenants(id),
  CONSTRAINT erp_bg_drop_point_fkey FOREIGN KEY (drop_point_id) REFERENCES public.erp_drop_points(id),
  CONSTRAINT erp_bg_promotion_fkey FOREIGN KEY (promotion_id) REFERENCES public.promotions(id),
  CONSTRAINT erp_bg_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.erp_staff(id)
);
CREATE TABLE public.erp_promotion_usage (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  tenant_id uuid NOT NULL DEFAULT '00000000-0000-0000-0000-000000000001'::uuid,
  promotion_id uuid NOT NULL,
  member_id uuid NOT NULL,
  order_id text,
  package_id uuid,
  group_order_id uuid,
  buddy_group_id uuid,
  reward_type text NOT NULL,
  reward_value numeric DEFAULT 0,
  reward_description text,
  is_redeemed boolean DEFAULT true,
  redeemed_at timestamp with time zone DEFAULT now(),
  notes text,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT erp_promotion_usage_pkey PRIMARY KEY (id),
  CONSTRAINT erp_pu_tenant_fkey FOREIGN KEY (tenant_id) REFERENCES public.erp_tenants(id),
  CONSTRAINT erp_pu_promotion_fkey FOREIGN KEY (promotion_id) REFERENCES public.promotions(id),
  CONSTRAINT erp_pu_member_fkey FOREIGN KEY (member_id) REFERENCES public.members(id),
  CONSTRAINT erp_pu_order_fkey FOREIGN KEY (order_id) REFERENCES public.orders(order_id),
  CONSTRAINT erp_pu_package_fkey FOREIGN KEY (package_id) REFERENCES public.pinto_packages(id),
  CONSTRAINT erp_pu_group_fkey FOREIGN KEY (group_order_id) REFERENCES public.erp_group_orders(id),
  CONSTRAINT erp_pu_buddy_fkey FOREIGN KEY (buddy_group_id) REFERENCES public.erp_buddy_groups(id)
);
CREATE TABLE public.erp_vehicles (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  name text NOT NULL,
  vehicle_type text NOT NULL DEFAULT 'motorcycle'::text,
  license_plate text,
  fuel_type text NOT NULL DEFAULT 'gasohol95'::text,
  fuel_efficiency numeric NOT NULL DEFAULT 48,
  purchase_price numeric DEFAULT 55000,
  expected_lifespan_km numeric DEFAULT 100000,
  depreciation_per_km numeric DEFAULT 
CASE
    WHEN (expected_lifespan_km > (0)::numeric) THEN (purchase_price / expected_lifespan_km)
    ELSE (0)::numeric
END,
  maintenance_per_km numeric DEFAULT 0.5,
  insurance_annual numeric DEFAULT 3000,
  estimated_trips_per_year numeric DEFAULT 1000,
  is_active boolean DEFAULT true,
  is_default boolean DEFAULT false,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT erp_vehicles_pkey PRIMARY KEY (id)
);
CREATE TABLE public.erp_fuel_prices (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  fuel_type text NOT NULL UNIQUE,
  price_per_liter numeric NOT NULL,
  source text DEFAULT 'bangchak_api'::text,
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT erp_fuel_prices_pkey PRIMARY KEY (id)
);
CREATE TABLE public.erp_pickup_orders (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  order_id text,
  schedule_id uuid,
  member_id uuid,
  customer_name text,
  customer_phone text,
  pickup_date date NOT NULL DEFAULT CURRENT_DATE,
  pickup_time_confirmed time without time zone,
  actual_pickup_at timestamp with time zone,
  status text NOT NULL DEFAULT 'pending'::text,
  cancel_reason text,
  auto_expire_days integer DEFAULT 3,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT erp_pickup_orders_pkey PRIMARY KEY (id)
);